CREATE ROLE loader_admin  SUPERUSER;
CREATE ROLE etl_runner;
CREATE ROLE app_api;
CREATE ROLE app_readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA admin GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO etl_runner;
