version: '3.3'

services:
  api-cache-db:
    container_name: api-cache-db-${API_VERSION}
    # latest versions fails silently and stops the container; see https://github.com/Snapchat/KeyDB/issues/802
    image: eqalpha/keydb:x86_64_v6.3.3
    restart: always
    ports:
      - ${KEYDB_PORT}:6379
    # the bind 0.0.0.0 and protected-mode no allow it to be accessed by the host machine
    # need to re-evaluate for production deployment
    # note: multi-master requires active replication
    # command: keydb-server --multi-master yes --protected-mode no --bind 0.0.0.0
    command: keydb-server --protected-mode no --bind 0.0.0.0
    volumes:
      - ${KEYDB_DATA_DIR}:/data


  api-static-db:
    container_name: api-static-db-${API_VERSION}
    image: postgres:15
    restart: always
    ports:
      - ${PG_PORT}:5432
    environment:
      POSTGRES_USER: ${PG_ADMIN_USER}
      POSTGRES_PASSWORD: ${PG_ADMIN_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_INITDB_ARGS: --auth-host=md5 --auth-local=md5
    volumes:
      - ${PG_DATA_DIR}:/var/lib/postgresql/data
      - ${PG_ENTRYPOINT}:/docker-entrypoint-initdb.d/

  api-static-db-init:
    container_name: init-${API_VERSION}
    image: niagads-api-init
    command: tail -F anything # this is to keep it running so we don't have to remount /scripts
    depends_on:
      - api-static-db
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
          BUILD: ${BUILD}
    volumes:
      - ${SCRIPTS_DIR}:/scripts
      - ${LOG_DIR}:/logs
      - ${FILES_DIR}:/files