version: '3.3'

services:
  app-db:
    container_name: app-db-${API_VERSION}
    image: postgres:15
    restart: always
    ports:
      - ${PG_PORT}:5432
    environment:
      POSTGRES_USER: ${PG_ADMIN_USER}
      POSTGRES_PASSWORD: ${PG_ADMIN_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_INITDB_ARGS: --auth-host=md5 --auth-local=md5
    volumes:
      - ${PG_DATA_DIR}:/var/lib/postgresql/data
      - ${PG_ENTRYPOINT}:/docker-entrypoint-initdb.d/

  app-db-init:
    container_name: init-${API_VERSION}
    image: niagads-api-init
    command: tail -F anything # this is to keep it running so we don't have to remount /scripts
    depends_on:
      - app-db
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
          BUILD: ${BUILD}
    volumes:
      - ${SCRIPTS_DIR}:/scripts
      - ${LOG_DIR}:/logs