""" "update_interval_bin"

Revision ID: 0e1860eae982
Revises: 2c33d393d0ed
Create Date: 2026-04-01 18:27:12.469775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import niagads.database.decorators
import pgvector.sqlalchemy.vector
import sqlalchemy_utils.types.ltree

# revision identifiers, used by Alembic.
revision: str = '0e1860eae982'
down_revision: Union[str, None] = '2c33d393d0ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intervalbin', sa.Column('bin_level', sa.Integer(), nullable=False), schema='reference')
    op.drop_column('intervalbin', 'path', schema='reference')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intervalbin', sa.Column('path', sa.VARCHAR(length=350), autoincrement=False, nullable=False), schema='reference')
    op.drop_column('intervalbin', 'bin_level', schema='reference')
    # ### end Alembic commands ###
