"""add cohorts to track

Revision ID: 110c98d804f0
Revises: 13e014654c46
Create Date: 2025-05-05 16:01:26.099369

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "110c98d804f0"
down_revision: Union[str, None] = "13e014654c46"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "track",
        sa.Column("cohorts", sa.ARRAY(sa.String()), nullable=False),
        schema="dataset",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("track", "cohorts", schema="dataset")
    # ### end Alembic commands ###
