"""make cohorts nullable

Revision ID: 19ad973d6dd4
Revises: 110c98d804f0
Create Date: 2025-05-09 12:53:16.885402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '19ad973d6dd4'
down_revision: Union[str, None] = '110c98d804f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('track', 'cohorts',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True,
               schema='metadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('track', 'cohorts',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False,
               schema='metadata')
    # ### end Alembic commands ###
