""" "adjust unique constraint on gene.annotation_evidence"

Revision ID: 23770b2f34a2
Revises: 2f82dc461aa6
Create Date: 2026-04-16 00:59:26.229127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import niagads.database.decorators
import pgvector.sqlalchemy.vector
import sqlalchemy_utils.types.ltree

# revision identifiers, used by Alembic.
revision: str = '23770b2f34a2'
down_revision: Union[str, None] = '2f82dc461aa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_gene_annotation_evidence', 'annotationevidence', schema='gene', type_='unique')
    op.create_unique_constraint('uq_gene_annotation_evidence', 'annotationevidence', ['evidence_code_id', 'table_id', 'row_id', 'qualifiers'], schema='gene')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_gene_annotation_evidence', 'annotationevidence', schema='gene', type_='unique')
    op.create_unique_constraint('uq_gene_annotation_evidence', 'annotationevidence', ['evidence_code_id', 'table_id', 'row_id'], schema='gene')
    # ### end Alembic commands ###
