""" "add linking tables for nested ontology terms and mesh-term based concepts"

Revision ID: 27cd812141a6
Revises: bc48b248ceb0
Create Date: 2026-08-27 12:09:17.496339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import niagads.database.decorators
import pgvector.sqlalchemy.vector
import sqlalchemy_utils.types.ltree

# revision identifiers, used by Alembic.
revision: str = '27cd812141a6'
down_revision: Union[str, None] = 'bc48b248ceb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trackconcept',
    sa.Column('track_concept_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('creation_date', niagads.database.decorators.AutoDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modification_date', niagads.database.decorators.AutoDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['admin.etlrun.etl_run_id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['reference.ontologyterm.ontology_term_id'], ),
    sa.PrimaryKeyConstraint('track_concept_id'),
    schema='dataset'
    )
    op.create_index(op.f('ix_dataset_trackconcept_run_id'), 'trackconcept', ['run_id'], unique=False, schema='dataset')
    op.create_index(op.f('ix_dataset_trackconcept_term_id'), 'trackconcept', ['term_id'], unique=False, schema='dataset')
    op.create_table('trackcontext',
    sa.Column('track_context_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('context', sa.Enum('BIOSAMPLE', 'PHENOTYPE', 'EXPERIMENT', name='trackcontexttype', native_enum=False), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('creation_date', niagads.database.decorators.AutoDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modification_date', niagads.database.decorators.AutoDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("context in ('BIOSAMPLE', 'PHENOTYPE', 'EXPERIMENT')", name='check_context'),
    sa.ForeignKeyConstraint(['run_id'], ['admin.etlrun.etl_run_id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['reference.ontologyterm.ontology_term_id'], ),
    sa.PrimaryKeyConstraint('track_context_id'),
    schema='dataset'
    )
    op.create_index(op.f('ix_dataset_trackcontext_context'), 'trackcontext', ['context'], unique=False, schema='dataset')
    op.create_index(op.f('ix_dataset_trackcontext_run_id'), 'trackcontext', ['run_id'], unique=False, schema='dataset')
    op.create_index(op.f('ix_dataset_trackcontext_term_id'), 'trackcontext', ['term_id'], unique=False, schema='dataset')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dataset_trackcontext_term_id'), table_name='trackcontext', schema='dataset')
    op.drop_index(op.f('ix_dataset_trackcontext_run_id'), table_name='trackcontext', schema='dataset')
    op.drop_index(op.f('ix_dataset_trackcontext_context'), table_name='trackcontext', schema='dataset')
    op.drop_table('trackcontext', schema='dataset')
    op.drop_index(op.f('ix_dataset_trackconcept_term_id'), table_name='trackconcept', schema='dataset')
    op.drop_index(op.f('ix_dataset_trackconcept_run_id'), table_name='trackconcept', schema='dataset')
    op.drop_table('trackconcept', schema='dataset')
    # ### end Alembic commands ###
