""" "gene model and genomic range update"

Revision ID: 29b512b4986d
Revises: 9a6803b55ca8
Create Date: 2026-04-03 21:00:01.210145

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import niagads.database.decorators
import pgvector.sqlalchemy.vector
import sqlalchemy_utils.types.ltree

# revision identifiers, used by Alembic.
revision: str = "29b512b4986d"
down_revision: Union[str, None] = "9a6803b55ca8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "trackinterval",
        sa.Column("span", niagads.database.decorators.RangeType(), nullable=False),
        schema="dataset",
    )
    op.add_column(
        "trackinterval",
        sa.Column(
            "strand", sa.Enum("+", "-", name="strand", native_enum=False), nullable=True
        ),
        schema="dataset",
    )
    op.drop_index(
        "ix_dataset_trackinterval__genomic_region",
        table_name="trackinterval",
        schema="dataset",
        postgresql_using="gist",
    )
    op.create_index(
        "ix_dataset_trackinterval__span",
        "trackinterval",
        ["span"],
        unique=False,
        schema="dataset",
        postgresql_using="gist",
    )
    op.drop_column("trackinterval", "genomic_region", schema="dataset")
    op.add_column(
        "exon", sa.Column("rank", sa.Integer(), nullable=False), schema="gene"
    )
    op.add_column(
        "exon",
        sa.Column("span", niagads.database.decorators.RangeType(), nullable=False),
        schema="gene",
    )
    op.add_column(
        "exon",
        sa.Column(
            "strand", sa.Enum("+", "-", name="strand", native_enum=False), nullable=True
        ),
        schema="gene",
    )
    op.drop_index(
        "ix_gene_exon__genomic_region",
        table_name="exon",
        schema="gene",
        postgresql_using="gist",
    )
    op.create_index(
        "ix_gene_exon__span",
        "exon",
        ["span"],
        unique=False,
        schema="gene",
        postgresql_using="gist",
    )
    op.drop_column("exon", "genomic_region", schema="gene")
    op.add_column(
        "gene",
        sa.Column("span", niagads.database.decorators.RangeType(), nullable=False),
        schema="gene",
    )
    op.add_column(
        "gene",
        sa.Column(
            "strand", sa.Enum("+", "-", name="strand", native_enum=False), nullable=True
        ),
        schema="gene",
    )
    op.drop_index(
        "ix_gene_gene__genomic_region",
        table_name="gene",
        schema="gene",
        postgresql_using="gist",
    )
    op.create_index(
        "ix_gene_gene__span",
        "gene",
        ["span"],
        unique=False,
        schema="gene",
        postgresql_using="gist",
    )
    op.drop_column("gene", "genomic_region", schema="gene")
    op.add_column(
        "transcript",
        sa.Column("name", sa.String(length=50), nullable=True),
        schema="gene",
    )
    op.add_column(
        "transcript",
        sa.Column("is_canonical", sa.Boolean(), nullable=True),
        schema="gene",
    )
    op.add_column(
        "transcript",
        sa.Column("span", niagads.database.decorators.RangeType(), nullable=False),
        schema="gene",
    )
    op.add_column(
        "transcript",
        sa.Column(
            "strand", sa.Enum("+", "-", name="strand", native_enum=False), nullable=True
        ),
        schema="gene",
    )
    op.drop_index(
        "ix_gene_transcript__genomic_region",
        table_name="transcript",
        schema="gene",
        postgresql_using="gist",
    )
    op.create_index(
        "ix_gene_transcript__span",
        "transcript",
        ["span"],
        unique=False,
        schema="gene",
        postgresql_using="gist",
    )
    op.create_index(
        op.f("ix_gene_transcript_is_canonical"),
        "transcript",
        ["is_canonical"],
        unique=False,
        schema="gene",
    )
    op.create_index(
        op.f("ix_gene_transcript_name"),
        "transcript",
        ["name"],
        unique=False,
        schema="gene",
    )
    op.drop_column("transcript", "genomic_region", schema="gene")
    op.add_column(
        "intervalbin",
        sa.Column(
            "strand", sa.Enum("+", "-", name="strand", native_enum=False), nullable=True
        ),
        schema="reference",
    )
    op.drop_index(
        "ix_reference_intervalbin__genomic_region",
        table_name="intervalbin",
        schema="reference",
        postgresql_using="gist",
    )
    op.alter_column(
        "intervalbin", "genomic_region", new_column_name="span", schema="reference"
    )
    op.create_index(
        "ix_reference_intervalbin__span",
        "intervalbin",
        ["span"],
        unique=False,
        schema="reference",
        postgresql_using="gist",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "intervalbin",
        sa.Column(
            "genomic_region",
            postgresql.INT4RANGE(),
            autoincrement=False,
            nullable=False,
        ),
        schema="reference",
    )
    op.drop_index(
        "ix_reference_intervalbin__span",
        table_name="intervalbin",
        schema="reference",
        postgresql_using="gist",
    )
    op.create_index(
        "ix_reference_intervalbin__genomic_region",
        "intervalbin",
        ["genomic_region"],
        unique=False,
        schema="reference",
        postgresql_using="gist",
    )
    op.drop_column("intervalbin", "strand", schema="reference")
    op.drop_column("intervalbin", "span", schema="reference")
    op.add_column(
        "transcript",
        sa.Column(
            "genomic_region",
            postgresql.INT4RANGE(),
            autoincrement=False,
            nullable=False,
        ),
        schema="gene",
    )
    op.drop_index(
        op.f("ix_gene_transcript_name"), table_name="transcript", schema="gene"
    )
    op.drop_index(
        op.f("ix_gene_transcript_is_canonical"), table_name="transcript", schema="gene"
    )
    op.drop_index(
        "ix_gene_transcript__span",
        table_name="transcript",
        schema="gene",
        postgresql_using="gist",
    )
    op.create_index(
        "ix_gene_transcript__genomic_region",
        "transcript",
        ["genomic_region"],
        unique=False,
        schema="gene",
        postgresql_using="gist",
    )
    op.drop_column("transcript", "strand", schema="gene")
    op.drop_column("transcript", "span", schema="gene")
    op.drop_column("transcript", "is_canonical", schema="gene")
    op.drop_column("transcript", "name", schema="gene")
    op.add_column(
        "gene",
        sa.Column(
            "genomic_region",
            postgresql.INT4RANGE(),
            autoincrement=False,
            nullable=False,
        ),
        schema="gene",
    )
    op.drop_index(
        "ix_gene_gene__span", table_name="gene", schema="gene", postgresql_using="gist"
    )
    op.create_index(
        "ix_gene_gene__genomic_region",
        "gene",
        ["genomic_region"],
        unique=False,
        schema="gene",
        postgresql_using="gist",
    )
    op.drop_column("gene", "strand", schema="gene")
    op.drop_column("gene", "span", schema="gene")
    op.add_column(
        "exon",
        sa.Column(
            "genomic_region",
            postgresql.INT4RANGE(),
            autoincrement=False,
            nullable=False,
        ),
        schema="gene",
    )
    op.drop_index(
        "ix_gene_exon__span", table_name="exon", schema="gene", postgresql_using="gist"
    )
    op.create_index(
        "ix_gene_exon__genomic_region",
        "exon",
        ["genomic_region"],
        unique=False,
        schema="gene",
        postgresql_using="gist",
    )
    op.drop_column("exon", "strand", schema="gene")
    op.drop_column("exon", "span", schema="gene")
    op.drop_column("exon", "rank", schema="gene")

    op.drop_index(
        "ix_dataset_trackinterval__span",
        table_name="trackinterval",
        schema="dataset",
        postgresql_using="gist",
    )
    op.alter_column(
        "intervalbin", "span", new_column_name="genomic_region", schema="reference"
    )

    op.create_index(
        "ix_dataset_trackinterval__genomic_region",
        "trackinterval",
        ["genomic_region"],
        unique=False,
        schema="dataset",
        postgresql_using="gist",
    )
    op.drop_column("trackinterval", "strand", schema="dataset")

    # ### end Alembic commands ###
