""" "update field names"

Revision ID: 29ce62d180de
Revises: e12928ecde8e
Create Date: 2026-10-08 22:44:03.883596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import niagads.database.decorators
import pgvector.sqlalchemy.vector
import sqlalchemy_utils.types.ltree

# revision identifiers, used by Alembic.
revision: str = '29ce62d180de'
down_revision: Union[str, None] = 'e12928ecde8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track', sa.Column('track_type_id', sa.Integer(), nullable=True), schema='dataset')
    op.drop_index('ix_dataset_track_dataset_type_id', table_name='track', schema='dataset')
    op.create_index(op.f('ix_dataset_track_track_type_id'), 'track', ['track_type_id'], unique=False, schema='dataset')
    op.drop_constraint('track_dataset_type_id_fkey', 'track', schema='dataset', type_='foreignkey')
    op.create_foreign_key(None, 'track', 'ontologyterm', ['track_type_id'], ['ontology_term_id'], source_schema='dataset', referent_schema='reference')
    op.drop_column('track', 'dataset_type_id', schema='dataset')
    op.add_column('variantassociation', sa.Column('effect_direction', sa.String(length=2), nullable=False), schema='results')
    op.add_column('variantassociation', sa.Column('test_allele', sa.TEXT(), nullable=True), schema='results')
    op.drop_column('variantassociation', 'beta_sign', schema='results')
    op.drop_column('variantassociation', 'allele', schema='results')
    op.add_column('varianttraitassociation', sa.Column('test_allele', sa.String(length=350), nullable=True), schema='results')
    op.drop_column('varianttraitassociation', 'allele', schema='results')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('varianttraitassociation', sa.Column('allele', sa.VARCHAR(length=350), autoincrement=False, nullable=True), schema='results')
    op.drop_column('varianttraitassociation', 'test_allele', schema='results')
    op.add_column('variantassociation', sa.Column('allele', sa.TEXT(), autoincrement=False, nullable=True), schema='results')
    op.add_column('variantassociation', sa.Column('beta_sign', sa.VARCHAR(length=2), autoincrement=False, nullable=False), schema='results')
    op.drop_column('variantassociation', 'test_allele', schema='results')
    op.drop_column('variantassociation', 'effect_direction', schema='results')
    op.add_column('track', sa.Column('dataset_type_id', sa.INTEGER(), autoincrement=False, nullable=False), schema='dataset')
    op.drop_constraint(None, 'track', schema='dataset', type_='foreignkey')
    op.create_foreign_key('track_dataset_type_id_fkey', 'track', 'ontologyterm', ['dataset_type_id'], ['ontology_term_id'], source_schema='dataset', referent_schema='reference')
    op.drop_index(op.f('ix_dataset_track_track_type_id'), table_name='track', schema='dataset')
    op.create_index('ix_dataset_track_dataset_type_id', 'track', ['dataset_type_id'], unique=False, schema='dataset')
    op.drop_column('track', 'track_type_id', schema='dataset')
    # ### end Alembic commands ###
