""" "genome reference"

Revision ID: 2c33d393d0ed
Revises: d5f293771db3
Create Date: 2026-03-31 11:20:41.439476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import niagads.database.decorators
import pgvector.sqlalchemy.vector
import sqlalchemy_utils.types.ltree

# revision identifiers, used by Alembic.
revision: str = '2c33d393d0ed'
down_revision: Union[str, None] = 'd5f293771db3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genomereference',
    sa.Column('genome_reference_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chromosome', sa.String(), nullable=False),
    sa.Column('genome_build', sa.Enum('GRCh37', 'GRCh38', name='GenomeBuild', native_enum=False), nullable=False),
    sa.Column('aliases', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('chromosome_length', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('creation_date', niagads.database.decorators.AutoDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modification_date', niagads.database.decorators.AutoDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("genome_build in ('GRCh37', 'GRCh38')", name='check_genome_build'),
    sa.ForeignKeyConstraint(['run_id'], ['admin.etlrun.etl_run_id'], ),
    sa.PrimaryKeyConstraint('genome_reference_id'),
    schema='reference'
    )
    op.create_index(op.f('ix_reference_genomereference_chromosome'), 'genomereference', ['chromosome'], unique=False, schema='reference')
    op.create_index(op.f('ix_reference_genomereference_genome_build'), 'genomereference', ['genome_build'], unique=False, schema='reference')
    op.create_index(op.f('ix_reference_genomereference_run_id'), 'genomereference', ['run_id'], unique=False, schema='reference')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reference_genomereference_run_id'), table_name='genomereference', schema='reference')
    op.drop_index(op.f('ix_reference_genomereference_genome_build'), table_name='genomereference', schema='reference')
    op.drop_index(op.f('ix_reference_genomereference_chromosome'), table_name='genomereference', schema='reference')
    op.drop_table('genomereference', schema='reference')
    # ### end Alembic commands ###
