""" "create shared base and remove source_id from all gene annotation tables"

Revision ID: 2f82dc461aa6
Revises: ec7d5289aaac
Create Date: 2026-04-14 13:27:13.679429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import niagads.database.decorators
import pgvector.sqlalchemy.vector
import sqlalchemy_utils.types.ltree

# revision identifiers, used by Alembic.
revision: str = '2f82dc461aa6'
down_revision: Union[str, None] = 'ec7d5289aaac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_gene_annotationevidence_source_id', table_name='annotationevidence', schema='gene')
    op.drop_column('annotationevidence', 'source_id', schema='gene')
    op.drop_index('ix_gene_goassociation_source_id', table_name='goassociation', schema='gene')
    op.drop_column('goassociation', 'source_id', schema='gene')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goassociation', sa.Column('source_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False), schema='gene')
    op.create_index('ix_gene_goassociation_source_id', 'goassociation', ['source_id'], unique=False, schema='gene')
    op.add_column('annotationevidence', sa.Column('source_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False), schema='gene')
    op.create_index('ix_gene_annotationevidence_source_id', 'annotationevidence', ['source_id'], unique=False, schema='gene')
    # ### end Alembic commands ###
