"""create index schema and add datasetinterval table

Revision ID: 380bbd3b1ca8
Revises: 861b41eb4f51
Create Date: 2025-06-24 14:18:19.276730

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils import LtreeType


# revision identifiers, used by Alembic.
revision: str = "380bbd3b1ca8"
down_revision: Union[str, None] = "861b41eb4f51"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS index")  # added by fossilfriend
    op.execute("CREATE EXTENSION IF NOT EXISTS ltree")  # added by fossilfriend

    op.create_table(
        "datasetinterval",
        sa.Column(
            "dataset_interval_id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("bin_index", LtreeType(), nullable=False),
        sa.Column("track_id", sa.String(), nullable=False),
        sa.Column("num_hits", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("dataset_interval_id"),
        schema="index",
    )
    op.create_index(
        "ix_index_bin_index",
        "datasetinterval",
        ["bin_index"],
        unique=False,
        schema="index",
        postgresql_using="gist",
    )
    op.create_index(
        "ix_index_datasetinterval_track_id",
        "datasetinterval",
        ["track_id"],
        unique=False,
        schema="index",
        postgresql_include=["num_hits"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_index_datasetinterval_track_id",
        table_name="datasetinterval",
        schema="index",
        postgresql_include=["num_hits"],
    )
    op.drop_index(
        "ix_index_bin_index",
        table_name="datasetinterval",
        schema="index",
        postgresql_using="gist",
    )
    op.drop_table("datasetinterval", schema="index")
    # ### end Alembic commands ###
