""" "add is_test_run column to ETLRun table"

Revision ID: 50ce76e266e0
Revises: 52008ce12f18
Create Date: 2026-03-20 09:30:18.873387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import niagads.database.decorators
import pgvector.sqlalchemy.vector
import sqlalchemy_utils.types.ltree

# revision identifiers, used by Alembic.
revision: str = '50ce76e266e0'
down_revision: Union[str, None] = '52008ce12f18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etlrun', sa.Column('is_test_run', sa.Boolean(), nullable=False), schema='admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('etlrun', 'is_test_run', schema='admin')
    # ### end Alembic commands ###
