""" "remove track store"

Revision ID: 52008ce12f18
Revises: e19f10fad55e
Create Date: 2026-03-18 08:39:19.591713

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import niagads.database.decorators
import pgvector.sqlalchemy.vector
import sqlalchemy_utils.types.ltree

# revision identifiers, used by Alembic.
revision: str = "52008ce12f18"
down_revision: Union[str, None] = "e19f10fad55e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "collection",
        sa.Column("is_filer_collection", sa.Boolean(), nullable=False),
        schema="dataset",
    )
    op.add_column(
        "collection",
        sa.Column("external_database_id", sa.Integer(), nullable=True),
        schema="dataset",
    )
    op.add_column(
        "collection",
        sa.Column("source_id", sa.String(length=50), nullable=True),
        schema="dataset",
    )
    op.drop_index(
        "ix_dataset_collection_data_store", table_name="collection", schema="dataset"
    )
    op.drop_index(
        "ix_metadata_collection_data_store",
        table_name="collection",
        schema="dataset",
        postgresql_include=["name", "description", "tracks_are_sharded"],
    )
    op.create_index(
        op.f("ix_dataset_collection_external_database_id"),
        "collection",
        ["external_database_id"],
        unique=False,
        schema="dataset",
    )
    op.create_index(
        op.f("ix_dataset_collection_source_id"),
        "collection",
        ["source_id"],
        unique=False,
        schema="dataset",
    )
    op.create_index(
        "ix_metadata_collection_is_filer_collection_true",
        "collection",
        ["is_filer_collection"],
        unique=False,
        schema="dataset",
        postgresql_where=sa.text("is_filer_collection = true"),
    )
    op.create_foreign_key(
        None,
        "collection",
        "externaldatabase",
        ["external_database_id"],
        ["external_database_id"],
        source_schema="dataset",
        referent_schema="reference",
    )
    op.drop_column("collection", "data_store", schema="dataset")
    op.add_column(
        "track",
        sa.Column("is_filer_track", sa.Boolean(), nullable=False),
        schema="dataset",
    )
    op.drop_index("ix_dataset_track_data_store", table_name="track", schema="dataset")
    op.create_index(
        "ix_metadata_track_is_filer_track_true",
        "track",
        ["is_filer_track"],
        unique=False,
        schema="dataset",
        postgresql_where=sa.text("is_filer_track = true"),
    )
    op.drop_column("track", "data_store", schema="dataset")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "track",
        sa.Column(
            "data_store", sa.VARCHAR(length=10), autoincrement=False, nullable=False
        ),
        schema="dataset",
    )
    op.drop_index(
        "ix_metadata_track_is_filer_track_true",
        table_name="track",
        schema="dataset",
        postgresql_where=sa.text("is_filer_track = true"),
    )
    op.create_index(
        "ix_dataset_track_data_store",
        "track",
        ["data_store"],
        unique=False,
        schema="dataset",
    )
    op.drop_column("track", "is_filer_track", schema="dataset")
    op.add_column(
        "collection",
        sa.Column(
            "data_store", sa.VARCHAR(length=10), autoincrement=False, nullable=False
        ),
        schema="dataset",
    )
    op.drop_constraint(None, "collection", schema="dataset", type_="foreignkey")
    op.drop_index(
        "ix_metadata_collection_is_filer_collection_true",
        table_name="collection",
        schema="dataset",
        postgresql_where=sa.text("is_filer_track = true"),
    )
    op.drop_index(
        op.f("ix_dataset_collection_source_id"),
        table_name="collection",
        schema="dataset",
    )
    op.drop_index(
        op.f("ix_dataset_collection_external_database_id"),
        table_name="collection",
        schema="dataset",
    )
    op.create_index(
        "ix_metadata_collection_data_store",
        "collection",
        ["data_store"],
        unique=False,
        schema="dataset",
        postgresql_include=["name", "description", "tracks_are_sharded"],
    )
    op.create_index(
        "ix_dataset_collection_data_store",
        "collection",
        ["data_store"],
        unique=False,
        schema="dataset",
    )
    op.drop_column("collection", "source_id", schema="dataset")
    op.drop_column("collection", "external_database_id", schema="dataset")
    op.drop_column("collection", "is_filer_collection", schema="dataset")
    # ### end Alembic commands ###
