""" "make message nullable"

Revision ID: 534a515922f4
Revises: 50ce76e266e0
Create Date: 2026-03-20 11:48:57.485508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import niagads.database.decorators
import pgvector.sqlalchemy.vector
import sqlalchemy_utils.types.ltree

# revision identifiers, used by Alembic.
revision: str = '534a515922f4'
down_revision: Union[str, None] = '50ce76e266e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('etlrun', 'message',
               existing_type=sa.TEXT(),
               nullable=True,
               schema='admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('etlrun', 'message',
               existing_type=sa.TEXT(),
               nullable=False,
               schema='admin')
    # ### end Alembic commands ###
