""" "add missing study_diagnosis field"

Revision ID: 5e374acb63e8
Revises: 585693ba2e34
Create Date: 2026-05-15 14:53:19.352079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import niagads.database.decorators
import pgvector.sqlalchemy.vector
import sqlalchemy_utils.types.ltree

# revision identifiers, used by Alembic.
revision: str = '5e374acb63e8'
down_revision: Union[str, None] = '585693ba2e34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track', sa.Column('study_diagnosis', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True), schema='dataset')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track', 'study_diagnosis', schema='dataset')
    # ### end Alembic commands ###
