"""add primary_key field to collection

Revision ID: 5e732b6e9650
Revises: 19ad973d6dd4
Create Date: 2025-06-20 10:28:03.393521

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5e732b6e9650"
down_revision: Union[str, None] = "19ad973d6dd4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "collection",
        sa.Column("primary_key", sa.String(), nullable=True),
        schema="dataset",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("collection", "primary_key", schema="dataset")
    # ### end Alembic commands ###
