""" "fix xref type enum"

Revision ID: 7a08c8e32e5f
Revises: f6c9bb8e3bb8
Create Date: 2026-04-07 18:57:22.635437

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import niagads.database.decorators
import pgvector.sqlalchemy.vector
import sqlalchemy_utils.types.ltree

# revision identifiers, used by Alembic.
revision: str = "7a08c8e32e5f"
down_revision: Union[str, None] = "f6c9bb8e3bb8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "xref",
        "xref_category",
        existing_type=sa.Enum(
            "IDENTIFIER",
            "LOCUS",
            "PUBLICATION",
            "RESOURCE_LINK",
            "CLASSIFICATION",
            "GROUP_MEMBERSHIP",
            "ORTHOLOG",
            name="genexrefcategory",
            native_enum=False,
            create_constraint=False,
        ),
        type_=sa.Enum(
            "IDENTIFIER",
            "NOMENCLATURE",
            "LOCUS",
            "PUBLICATION",
            "RESOURCE_LINK",
            "CLASSIFICATION",
            "GROUP_MEMBERSHIP",
            "ORTHOLOG",
            name="genexrefcategory",
            native_enum=False,
            create_constraint=False,
        ),
        existing_nullable=False,
        schema="gene",
    )
    op.create_check_constraint(
        "check_xref_category",
        "xref",
        "xref_category in ('IDENTIFIER','NOMENCLATURE','LOCUS','PUBLICATION','RESOURCE_LINK','CLASSIFICATION','GROUP_MEMBERSHIP','ORTHOLOG')",
        schema="gene",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # this is a bug fix, no downgrade
