""" "centralize embeddings"

Revision ID: 7d80ca04cf3b
Revises: a440afb1263f
Create Date: 2026-03-12 08:50:30.944757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import niagads.database.decorators
import pgvector.sqlalchemy.vector
import sqlalchemy_utils.types.ltree

# revision identifiers, used by Alembic.
revision: str = '7d80ca04cf3b'
down_revision: Union[str, None] = 'a440afb1263f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track', sa.Column('participant_phenotypes', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True), schema='dataset')
    op.drop_index('ix_dataset_track_embedding', table_name='track', schema='dataset', postgresql_using='hnsw')
    op.drop_index('ix_dataset_track_embedding_model', table_name='track', schema='dataset')
    op.drop_index('ix_dataset_track_embedding_run_id', table_name='track', schema='dataset')
    op.drop_constraint('track_embedding_run_id_fkey', 'track', schema='dataset', type_='foreignkey')
    op.drop_column('track', 'subject_phenotypes', schema='dataset')
    op.drop_column('track', 'embedding_date', schema='dataset')
    op.drop_column('track', 'embedding', schema='dataset')
    op.drop_column('track', 'embedding_run_id', schema='dataset')
    op.drop_column('track', 'embedding_hash', schema='dataset')
    op.drop_column('track', 'embedding_model', schema='dataset')
    op.add_column('chunkembedding', sa.Column('chunk_embedding_id', sa.Integer(), autoincrement=True, nullable=False), schema='ragdoc')
    op.add_column('chunkembedding', sa.Column('embedding_model', sa.String(length=250), nullable=True), schema='ragdoc')
    op.add_column('chunkembedding', sa.Column('embedding_hash', sa.LargeBinary(length=32), nullable=True), schema='ragdoc')
    op.add_column('chunkembedding', sa.Column('embedding_date', sa.TIMESTAMP(), nullable=True), schema='ragdoc')
    op.add_column('chunkembedding', sa.Column('embedding_run_id', sa.Integer(), nullable=True), schema='ragdoc')
    op.alter_column('chunkembedding', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               nullable=True,
               schema='ragdoc')
    op.drop_index('ix_embedding_vector_hnsw', table_name='chunkembedding', schema='ragdoc', postgresql_using='hnsw')
    op.drop_index('ix_ragdoc_chunkembedding_model_id', table_name='chunkembedding', schema='ragdoc')
    op.drop_constraint('uq_embedding_chunk', 'chunkembedding', schema='ragdoc', type_='unique')
    op.create_unique_constraint('uq_embedding_chunk', 'chunkembedding', ['chunk_metadata_id', 'embedding_model', 'chunk_hash'], schema='ragdoc')
    op.create_index('ix_ragdoc_chunkembedding_embedding', 'chunkembedding', ['embedding'], unique=False, schema='ragdoc', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_ragdoc_chunkembedding_embedding_model'), 'chunkembedding', ['embedding_model'], unique=False, schema='ragdoc')
    op.create_index(op.f('ix_ragdoc_chunkembedding_embedding_run_id'), 'chunkembedding', ['embedding_run_id'], unique=False, schema='ragdoc')
    op.create_foreign_key(None, 'chunkembedding', 'etlrun', ['embedding_run_id'], ['etl_run_id'], source_schema='ragdoc', referent_schema='admin')
    op.drop_column('chunkembedding', 'embedding_id', schema='ragdoc')
    op.drop_column('chunkembedding', 'model_id', schema='ragdoc')
    op.add_column('chunkmetadata', sa.Column('document_type', sa.Enum('REFERENCE', 'ONTOLOGY', 'GENE', 'VARIANT', 'METADATA', 'DOCUMENT', name='RAGDocTypes', native_enum=False), nullable=False), schema='ragdoc')
    op.add_column('chunkmetadata', sa.Column('document_section', sa.String(length=64), server_default='FULL', nullable=False), schema='ragdoc')
    op.add_column('chunkmetadata', sa.Column('document_hash', sa.LargeBinary(length=32), nullable=True), schema='ragdoc')
    op.add_column('chunkmetadata', sa.Column('chunk_id', sa.String(length=128), nullable=False), schema='ragdoc')
    op.drop_constraint('uq_chunk_metadata', 'chunkmetadata', schema='ragdoc', type_='unique')
    op.create_unique_constraint('uq_chunk_metadata', 'chunkmetadata', ['table_id', 'row_id', 'document_section', 'chunk_index', 'chunk_hash'], schema='ragdoc')
    op.create_index(op.f('ix_ragdoc_chunkmetadata_chunk_id'), 'chunkmetadata', ['chunk_id'], unique=False, schema='ragdoc')
    op.create_index(op.f('ix_ragdoc_chunkmetadata_document_type'), 'chunkmetadata', ['document_type'], unique=False, schema='ragdoc')
    op.drop_column('chunkmetadata', 'section', schema='ragdoc')
    op.drop_column('chunkmetadata', 'doc_hash', schema='ragdoc')
    op.drop_index('ix_reference_ontologyterm_embedding', table_name='ontologyterm', schema='reference', postgresql_using='hnsw')
    op.drop_index('ix_reference_ontologyterm_embedding_model', table_name='ontologyterm', schema='reference')
    op.drop_index('ix_reference_ontologyterm_embedding_run_id', table_name='ontologyterm', schema='reference')
    op.drop_constraint('ontologyterm_embedding_run_id_fkey', 'ontologyterm', schema='reference', type_='foreignkey')
    op.drop_column('ontologyterm', 'embedding_model', schema='reference')
    op.drop_column('ontologyterm', 'embedding_date', schema='reference')
    op.drop_column('ontologyterm', 'embedding_run_id', schema='reference')
    op.drop_column('ontologyterm', 'embedding_hash', schema='reference')
    op.drop_column('ontologyterm', 'embedding', schema='reference')
    op.drop_index('ix_reference_pathway_embedding', table_name='pathway', schema='reference', postgresql_using='hnsw')
    op.drop_index('ix_reference_pathway_embedding_model', table_name='pathway', schema='reference')
    op.drop_index('ix_reference_pathway_embedding_run_id', table_name='pathway', schema='reference')
    op.drop_constraint('pathway_embedding_run_id_fkey', 'pathway', schema='reference', type_='foreignkey')
    op.drop_column('pathway', 'embedding_model', schema='reference')
    op.drop_column('pathway', 'embedding_date', schema='reference')
    op.drop_column('pathway', 'embedding_run_id', schema='reference')
    op.drop_column('pathway', 'embedding_hash', schema='reference')
    op.drop_column('pathway', 'embedding', schema='reference')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pathway', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), autoincrement=False, nullable=True), schema='reference')
    op.add_column('pathway', sa.Column('embedding_hash', postgresql.BYTEA(), autoincrement=False, nullable=True), schema='reference')
    op.add_column('pathway', sa.Column('embedding_run_id', sa.INTEGER(), autoincrement=False, nullable=True), schema='reference')
    op.add_column('pathway', sa.Column('embedding_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True), schema='reference')
    op.add_column('pathway', sa.Column('embedding_model', sa.VARCHAR(length=250), autoincrement=False, nullable=True), schema='reference')
    op.create_foreign_key('pathway_embedding_run_id_fkey', 'pathway', 'etlrun', ['embedding_run_id'], ['etl_run_id'], source_schema='reference', referent_schema='admin')
    op.create_index('ix_reference_pathway_embedding_run_id', 'pathway', ['embedding_run_id'], unique=False, schema='reference')
    op.create_index('ix_reference_pathway_embedding_model', 'pathway', ['embedding_model'], unique=False, schema='reference')
    op.create_index('ix_reference_pathway_embedding', 'pathway', ['embedding'], unique=False, schema='reference', postgresql_using='hnsw')
    op.add_column('ontologyterm', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), autoincrement=False, nullable=True), schema='reference')
    op.add_column('ontologyterm', sa.Column('embedding_hash', postgresql.BYTEA(), autoincrement=False, nullable=True), schema='reference')
    op.add_column('ontologyterm', sa.Column('embedding_run_id', sa.INTEGER(), autoincrement=False, nullable=True), schema='reference')
    op.add_column('ontologyterm', sa.Column('embedding_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True), schema='reference')
    op.add_column('ontologyterm', sa.Column('embedding_model', sa.VARCHAR(length=250), autoincrement=False, nullable=True), schema='reference')
    op.create_foreign_key('ontologyterm_embedding_run_id_fkey', 'ontologyterm', 'etlrun', ['embedding_run_id'], ['etl_run_id'], source_schema='reference', referent_schema='admin')
    op.create_index('ix_reference_ontologyterm_embedding_run_id', 'ontologyterm', ['embedding_run_id'], unique=False, schema='reference')
    op.create_index('ix_reference_ontologyterm_embedding_model', 'ontologyterm', ['embedding_model'], unique=False, schema='reference')
    op.create_index('ix_reference_ontologyterm_embedding', 'ontologyterm', ['embedding'], unique=False, schema='reference', postgresql_using='hnsw')
    op.add_column('chunkmetadata', sa.Column('doc_hash', postgresql.BYTEA(), autoincrement=False, nullable=True), schema='ragdoc')
    op.add_column('chunkmetadata', sa.Column('section', sa.VARCHAR(length=64), server_default=sa.text("'FULL'::character varying"), autoincrement=False, nullable=False), schema='ragdoc')
    op.drop_index(op.f('ix_ragdoc_chunkmetadata_document_type'), table_name='chunkmetadata', schema='ragdoc')
    op.drop_index(op.f('ix_ragdoc_chunkmetadata_chunk_id'), table_name='chunkmetadata', schema='ragdoc')
    op.drop_constraint('uq_chunk_metadata', 'chunkmetadata', schema='ragdoc', type_='unique')
    op.create_unique_constraint('uq_chunk_metadata', 'chunkmetadata', ['table_id', 'row_id', 'section', 'chunk_index', 'chunk_hash'], schema='ragdoc')
    op.drop_column('chunkmetadata', 'chunk_id', schema='ragdoc')
    op.drop_column('chunkmetadata', 'document_hash', schema='ragdoc')
    op.drop_column('chunkmetadata', 'document_section', schema='ragdoc')
    op.drop_column('chunkmetadata', 'document_type', schema='ragdoc')
    op.add_column('chunkembedding', sa.Column('model_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False), schema='ragdoc')
    op.add_column('chunkembedding', sa.Column('embedding_id', sa.INTEGER(), autoincrement=True, nullable=False), schema='ragdoc')
    op.drop_constraint(None, 'chunkembedding', schema='ragdoc', type_='foreignkey')
    op.drop_index(op.f('ix_ragdoc_chunkembedding_embedding_run_id'), table_name='chunkembedding', schema='ragdoc')
    op.drop_index(op.f('ix_ragdoc_chunkembedding_embedding_model'), table_name='chunkembedding', schema='ragdoc')
    op.drop_index('ix_ragdoc_chunkembedding_embedding', table_name='chunkembedding', schema='ragdoc', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_constraint('uq_embedding_chunk', 'chunkembedding', schema='ragdoc', type_='unique')
    op.create_unique_constraint('uq_embedding_chunk', 'chunkembedding', ['chunk_metadata_id', 'model_id', 'chunk_hash'], schema='ragdoc')
    op.create_index('ix_ragdoc_chunkembedding_model_id', 'chunkembedding', ['model_id'], unique=False, schema='ragdoc')
    op.create_index('ix_embedding_vector_hnsw', 'chunkembedding', ['embedding'], unique=False, schema='ragdoc', postgresql_using='hnsw')
    op.alter_column('chunkembedding', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               nullable=False,
               schema='ragdoc')
    op.drop_column('chunkembedding', 'embedding_run_id', schema='ragdoc')
    op.drop_column('chunkembedding', 'embedding_date', schema='ragdoc')
    op.drop_column('chunkembedding', 'embedding_hash', schema='ragdoc')
    op.drop_column('chunkembedding', 'embedding_model', schema='ragdoc')
    op.drop_column('chunkembedding', 'chunk_embedding_id', schema='ragdoc')
    op.add_column('track', sa.Column('embedding_model', sa.VARCHAR(length=250), autoincrement=False, nullable=True), schema='dataset')
    op.add_column('track', sa.Column('embedding_hash', postgresql.BYTEA(), autoincrement=False, nullable=True), schema='dataset')
    op.add_column('track', sa.Column('embedding_run_id', sa.INTEGER(), autoincrement=False, nullable=True), schema='dataset')
    op.add_column('track', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), autoincrement=False, nullable=True), schema='dataset')
    op.add_column('track', sa.Column('embedding_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True), schema='dataset')
    op.add_column('track', sa.Column('subject_phenotypes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True), schema='dataset')
    op.create_foreign_key('track_embedding_run_id_fkey', 'track', 'etlrun', ['embedding_run_id'], ['etl_run_id'], source_schema='dataset', referent_schema='admin')
    op.create_index('ix_dataset_track_embedding_run_id', 'track', ['embedding_run_id'], unique=False, schema='dataset')
    op.create_index('ix_dataset_track_embedding_model', 'track', ['embedding_model'], unique=False, schema='dataset')
    op.create_index('ix_dataset_track_embedding', 'track', ['embedding'], unique=False, schema='dataset', postgresql_using='hnsw')
    op.drop_column('track', 'participant_phenotypes', schema='dataset')
    # ### end Alembic commands ###
