""" "tgrm indexes and create synonym list column"

Revision ID: 7fd3ad2f135b
Revises: 27cd812141a6
Create Date: 2026-09-04 09:47:29.517499

"""

from typing import Sequence, Union

import niagads.database.decorators
import pgvector.sqlalchemy.vector
import sqlalchemy as sa
import sqlalchemy_utils.types.ltree
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7fd3ad2f135b"
down_revision: Union[str, None] = "27cd812141a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ontologyterm",
        sa.Column("synonym_list_str", sa.TEXT(), nullable=True),
        schema="reference",
    )
    op.drop_index(
        "ix_ontologyterm_term_trgm",
        table_name="ontologyterm",
        schema="reference",
        postgresql_using="gin",
    )
    op.create_index(
        "ix_ontology_term_definition_trgm",
        "ontologyterm",
        ["definition"],
        unique=False,
        schema="reference",
        postgresql_using="gin",
        postgresql_ops={"definition": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_ontology_term_synonyms_trgm",
        "ontologyterm",
        ["synonym_list_str"],
        unique=False,
        schema="reference",
        postgresql_using="gin",
        postgresql_ops={"synonym_list_str": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_ontology_term_term_trgm",
        "ontologyterm",
        ["term"],
        unique=False,
        schema="reference",
        postgresql_using="gin",
        postgresql_ops={"term": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###

    op.execute(sa.text("""
        UPDATE reference.ontologyterm
        SET synonym_list_str = array_to_string(synonyms, ' // ')
        WHERE synonyms IS NOT NULL
        """))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_ontology_term_term_trgm",
        table_name="ontologyterm",
        schema="reference",
        postgresql_using="gin",
        postgresql_ops={"term": "gin_trgm_ops"},
    )
    op.drop_index(
        "ix_ontology_term_synonyms_trgm",
        table_name="ontologyterm",
        schema="reference",
        postgresql_using="gin",
        postgresql_ops={"synonym_list_str": "gin_trgm_ops"},
    )
    op.drop_index(
        "ix_ontology_term_definition_trgm",
        table_name="ontologyterm",
        schema="reference",
        postgresql_using="gin",
        postgresql_ops={"definition": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_ontologyterm_term_trgm",
        "ontologyterm",
        ["term"],
        unique=False,
        schema="reference",
        postgresql_using="gin",
    )
    op.drop_column("ontologyterm", "synonym_list_str", schema="reference")
    # ### end Alembic commands ###
