"""make collection primary_key field non nullable and have unique index

Revision ID: 861b41eb4f51
Revises: 5e732b6e9650
Create Date: 2025-06-20 10:30:19.239171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '861b41eb4f51'
down_revision: Union[str, None] = '5e732b6e9650'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('collection', 'primary_key',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='metadata')
    op.create_index('ix_metadata_collection_primary_key_unique', 'collection', ['primary_key'], unique=True, schema='metadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_metadata_collection_primary_key_unique', table_name='collection', schema='metadata')
    op.alter_column('collection', 'primary_key',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='metadata')
    # ### end Alembic commands ###
