""" "add missing external database release to refsnpalias"

Revision ID: 8b0e7273166f
Revises: fc52f3adf778
Create Date: 2026-05-11 18:28:25.342244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import niagads.database.decorators
import pgvector.sqlalchemy.vector
import sqlalchemy_utils.types.ltree

# revision identifiers, used by Alembic.
revision: str = '8b0e7273166f'
down_revision: Union[str, None] = 'fc52f3adf778'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ref_snp_alias', sa.Column('external_database_id', sa.Integer(), nullable=False), schema='variant')
    op.create_foreign_key(None, 'ref_snp_alias', 'externaldatabase', ['external_database_id'], ['external_database_id'], source_schema='variant', referent_schema='reference')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ref_snp_alias', schema='variant', type_='foreignkey')
    op.drop_column('ref_snp_alias', 'external_database_id', schema='variant')
    # ### end Alembic commands ###
