""" "alter gene_type_id to map to ontology_term_id"

Revision ID: 955ccc8282d0
Revises: 0e1860eae982
Create Date: 2026-04-02 13:41:49.128498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import niagads.database.decorators
import pgvector.sqlalchemy.vector
import sqlalchemy_utils.types.ltree

# revision identifiers, used by Alembic.
revision: str = '955ccc8282d0'
down_revision: Union[str, None] = '0e1860eae982'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gene', sa.Column('gene_type_id', sa.Integer(), nullable=False), schema='gene')
    op.create_index(op.f('ix_gene_gene_gene_type_id'), 'gene', ['gene_type_id'], unique=False, schema='gene')
    op.create_foreign_key(None, 'gene', 'ontologyterm', ['gene_type_id'], ['ontology_term_id'], source_schema='gene', referent_schema='reference')
    op.drop_column('gene', 'gene_type', schema='gene')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gene', sa.Column('gene_type', sa.VARCHAR(length=150), autoincrement=False, nullable=False), schema='gene')
    op.drop_constraint(None, 'gene', schema='gene', type_='foreignkey')
    op.drop_index(op.f('ix_gene_gene_gene_type_id'), table_name='gene', schema='gene')
    op.drop_column('gene', 'gene_type_id', schema='gene')
    # ### end Alembic commands ###
