""" "gene_xref_update"

Revision ID: 9a6803b55ca8
Revises: 955ccc8282d0
Create Date: 2026-04-02 20:50:33.810197

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import niagads.database.decorators
import pgvector.sqlalchemy.vector
import sqlalchemy_utils.types.ltree

# revision identifiers, used by Alembic.
revision: str = "9a6803b55ca8"
down_revision: Union[str, None] = "955ccc8282d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "xref",
        sa.Column(
            "xref_category",
            sa.Enum(
                "IDENTIFIER",
                "LOCUS",
                "PUBLICATION",
                "RESOURCE_LINK",
                "CLASSIFICATION",
                "GROUP_MEMBERSHIP",
                "ORTHOLOG",
                name="genexrefcategory",
                native_enum=False,
            ),
            nullable=False,
        ),
        schema="gene",
    )
    op.add_column(
        "xref",
        sa.Column("xref_label", sa.String(length=50), nullable=True),
        schema="gene",
    )
    op.add_column(
        "xref",
        sa.Column("xref_value", sa.String(length=250), nullable=True),
        schema="gene",
    )
    op.add_column(
        "xref",
        sa.Column("ontology_term_id", sa.Integer(), nullable=True),
        schema="gene",
    )
    op.drop_constraint(
        "xref_external_database_id_source_id_key", "xref", schema="gene", type_="unique"
    )
    op.create_index(
        op.f("ix_gene_xref_ontology_term_id"),
        "xref",
        ["ontology_term_id"],
        unique=False,
        schema="gene",
    )
    op.create_index(
        op.f("ix_gene_xref_xref_category"),
        "xref",
        ["xref_category"],
        unique=False,
        schema="gene",
    )
    op.create_index(
        op.f("ix_gene_xref_xref_label"),
        "xref",
        ["xref_label"],
        unique=False,
        schema="gene",
    )
    op.create_index(
        op.f("ix_gene_xref_xref_value"),
        "xref",
        ["xref_value"],
        unique=False,
        schema="gene",
    )
    op.create_foreign_key(
        None,
        "xref",
        "ontologyterm",
        ["ontology_term_id"],
        ["ontology_term_id"],
        source_schema="gene",
        referent_schema="reference",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "xref", schema="gene", type_="foreignkey")
    op.drop_index(op.f("ix_gene_xref_xref_value"), table_name="xref", schema="gene")
    op.drop_index(op.f("ix_gene_xref_xref_label"), table_name="xref", schema="gene")
    op.drop_index(op.f("ix_gene_xref_xref_category"), table_name="xref", schema="gene")
    op.drop_index(
        op.f("ix_gene_xref_ontology_term_id"), table_name="xref", schema="gene"
    )
    op.create_unique_constraint(
        "xref_external_database_id_source_id_key",
        "xref",
        ["external_database_id", "source_id"],
        schema="gene",
    )
    op.drop_column("xref", "ontology_term_id", schema="gene")
    op.drop_column("xref", "xref_value", schema="gene")
    op.drop_column("xref", "xref_label", schema="gene")
    op.drop_column("xref", "xref_category", schema="gene")
    # ### end Alembic commands ###
