""" "create refsnpalias variant table"

Revision ID: 9fc415e7b82c
Revises: b6cb6e6eb91e
Create Date: 2026-05-11 18:11:15.961112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import niagads.database.decorators
import pgvector.sqlalchemy.vector
import sqlalchemy_utils.types.ltree

# revision identifiers, used by Alembic.
revision: str = '9fc415e7b82c'
down_revision: Union[str, None] = 'b6cb6e6eb91e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ref_snp_alias',
    sa.Column('ref_snp_alias_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ref_snp_id', sa.String(length=25), nullable=False),
    sa.Column('merged_ref_snp_id', sa.String(length=25), nullable=False),
    sa.Column('merge_build', sa.INTEGER(), nullable=False),
    sa.Column('merge_date', niagads.database.decorators.AutoDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('creation_date', niagads.database.decorators.AutoDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modification_date', niagads.database.decorators.AutoDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['admin.etlrun.etl_run_id'], ),
    sa.PrimaryKeyConstraint('ref_snp_alias_id'),
    schema='variant'
    )
    op.create_index(op.f('ix_variant_ref_snp_alias_merged_ref_snp_id'), 'ref_snp_alias', ['merged_ref_snp_id'], unique=False, schema='variant')
    op.create_index(op.f('ix_variant_ref_snp_alias_ref_snp_id'), 'ref_snp_alias', ['ref_snp_id'], unique=False, schema='variant')
    op.create_index(op.f('ix_variant_ref_snp_alias_run_id'), 'ref_snp_alias', ['run_id'], unique=False, schema='variant')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_variant_ref_snp_alias_run_id'), table_name='ref_snp_alias', schema='variant')
    op.drop_index(op.f('ix_variant_ref_snp_alias_ref_snp_id'), table_name='ref_snp_alias', schema='variant')
    op.drop_index(op.f('ix_variant_ref_snp_alias_merged_ref_snp_id'), table_name='ref_snp_alias', schema='variant')
    op.drop_table('ref_snp_alias', schema='variant')
    # ### end Alembic commands ###
