"""initialize admin schema

Revision ID: a02c08bd426e
Revises: 765dc0a086d4
Create Date: 2026-02-18 00:10:42.181196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a02c08bd426e'
down_revision: Union[str, None] = '765dc0a086d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etlrun',
    sa.Column('etl_run_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plugin_name', sa.String(length=150), nullable=False),
    sa.Column('plugin_version', sa.String(length=50), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAIL', 'RUNNING', native_enum=False), nullable=False),
    sa.Column('operation', sa.Enum('INSERT', 'UPDATE', 'LOAD', 'PATCH', 'DELETE', 'SKIP', native_enum=False), nullable=False),
    sa.Column('start_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('end_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('rows_processed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("operation in ('INSERT', 'UPDATE', 'LOAD', 'PATCH', 'DELETE', 'SKIP')", name='check_operation'),
    sa.CheckConstraint("status in ('SUCCESS', 'FAIL', 'RUNNING')", name='check_status'),
    sa.ForeignKeyConstraint(['run_id'], ['admin.etlrun.etl_run_id'], ),
    sa.PrimaryKeyConstraint('etl_run_id'),
    schema='admin'
    )
    op.create_index(op.f('ix_admin_etlrun_operation'), 'etlrun', ['operation'], unique=False, schema='admin')
    op.create_index(op.f('ix_admin_etlrun_run_id'), 'etlrun', ['run_id'], unique=False, schema='admin')
    op.create_index(op.f('ix_admin_etlrun_status'), 'etlrun', ['status'], unique=False, schema='admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_etlrun_status'), table_name='etlrun', schema='admin')
    op.drop_index(op.f('ix_admin_etlrun_run_id'), table_name='etlrun', schema='admin')
    op.drop_index(op.f('ix_admin_etlrun_operation'), table_name='etlrun', schema='admin')
    op.drop_table('etlrun', schema='admin')
    # ### end Alembic commands ###
