""" "initial table creation - all schemas"

Revision ID: a440afb1263f
Revises: 583401c0c89c
Create Date: 2026-03-05 09:13:12.818699

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import niagads.database.decorators
import pgvector.sqlalchemy.vector
import sqlalchemy_utils.types.ltree

# revision identifiers, used by Alembic.
revision: str = "a440afb1263f"
down_revision: Union[str, None] = "583401c0c89c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "etlrun",
        sa.Column("etl_run_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("plugin_name", sa.String(length=150), nullable=False),
        sa.Column("plugin_version", sa.String(length=50), nullable=True),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "SUCCESS", "FAIL", "RUNNING", name="ProcessStatus", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column(
            "operation",
            sa.Enum(
                "INSERT",
                "UPDATE",
                "LOAD",
                "PATCH",
                "DELETE",
                "SKIP",
                name="ETLOperation",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "start_time",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("end_time", sa.TIMESTAMP(), nullable=True),
        sa.Column("rows_processed", sa.Integer(), server_default="0", nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "operation in ('INSERT', 'UPDATE', 'LOAD', 'PATCH', 'DELETE', 'SKIP')",
            name="check_operation",
        ),
        sa.CheckConstraint(
            "status in ('SUCCESS', 'FAIL', 'RUNNING')", name="check_status"
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["admin.etlrun.etl_run_id"],
        ),
        sa.PrimaryKeyConstraint("etl_run_id"),
        schema="admin",
    )
    op.create_index(
        op.f("ix_admin_etlrun_operation"),
        "etlrun",
        ["operation"],
        unique=False,
        schema="admin",
    )
    op.create_index(
        op.f("ix_admin_etlrun_run_id"),
        "etlrun",
        ["run_id"],
        unique=False,
        schema="admin",
    )
    op.create_index(
        op.f("ix_admin_etlrun_status"),
        "etlrun",
        ["status"],
        unique=False,
        schema="admin",
    )
    op.create_table(
        "schemacatalog",
        sa.Column("schema_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("schema_id"),
        schema="admin",
    )
    op.create_index(
        op.f("ix_admin_schemacatalog_name"),
        "schemacatalog",
        ["name"],
        unique=True,
        schema="admin",
    )
    op.create_table(
        "tablecatalog",
        sa.Column("table_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("schema_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("table_primary_key", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["schema_id"],
            ["admin.schemacatalog.schema_id"],
        ),
        sa.PrimaryKeyConstraint("table_id"),
        sa.UniqueConstraint("schema_id", "name", name="uq_schema_table_name"),
        schema="admin",
    )
    op.create_index(
        op.f("ix_admin_tablecatalog_name"),
        "tablecatalog",
        ["name"],
        unique=False,
        schema="admin",
    )
    op.create_index(
        op.f("ix_admin_tablecatalog_schema_id"),
        "tablecatalog",
        ["schema_id"],
        unique=False,
        schema="admin",
    )
    op.create_table(
        "collection",
        sa.Column("collection_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("collection_key", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=False),
        sa.Column("tracks_are_sharded", sa.Boolean(), nullable=True),
        sa.Column(
            "data_store",
            sa.Enum(
                "GENOMICSDB",
                "FILER",
                "SHARED",
                name="TrackDataStore",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column(
            "creation_date",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "modification_date",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "data_store in ('GENOMICSDB', 'FILER', 'SHARED')", name="check_data_store"
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["admin.etlrun.etl_run_id"],
        ),
        sa.PrimaryKeyConstraint("collection_id"),
        schema="dataset",
    )
    op.create_index(
        op.f("ix_dataset_collection_data_store"),
        "collection",
        ["data_store"],
        unique=False,
        schema="dataset",
    )
    op.create_index(
        op.f("ix_dataset_collection_run_id"),
        "collection",
        ["run_id"],
        unique=False,
        schema="dataset",
    )
    op.create_index(
        "ix_metadata_collection_data_store",
        "collection",
        ["data_store"],
        unique=False,
        schema="dataset",
        postgresql_include=["name", "description", "tracks_are_sharded"],
    )
    op.create_index(
        "ix_metadata_collection_key_unique",
        "collection",
        ["collection_key"],
        unique=True,
        schema="dataset",
    )
    op.create_table(
        "externaldatabase",
        sa.Column(
            "external_database_id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("name", sa.String(length=250), nullable=False),
        sa.Column("database_key", sa.String(length=32), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("url", sa.String(length=300), nullable=True),
        sa.Column("version", sa.String(length=50), nullable=True),
        sa.Column("download_url", sa.String(length=300), nullable=True),
        sa.Column("download_date", sa.TIMESTAMP(), nullable=True),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column(
            "creation_date",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "modification_date",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["admin.etlrun.etl_run_id"],
        ),
        sa.PrimaryKeyConstraint("external_database_id"),
        sa.UniqueConstraint("name", "version", name="uq_externaldatabase_name_version"),
        schema="reference",
    )
    op.create_index(
        op.f("ix_reference_externaldatabase_database_key"),
        "externaldatabase",
        ["database_key"],
        unique=False,
        schema="reference",
    )
    op.create_index(
        op.f("ix_reference_externaldatabase_name"),
        "externaldatabase",
        ["name"],
        unique=False,
        schema="reference",
    )
    op.create_index(
        op.f("ix_reference_externaldatabase_run_id"),
        "externaldatabase",
        ["run_id"],
        unique=False,
        schema="reference",
    )
    op.create_table(
        "intervalbin",
        sa.Column("interval_bin_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("path", sa.String(length=350), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column(
            "creation_date",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "modification_date",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "chromosome",
            sa.Enum(
                "1",
                "2",
                "3",
                "4",
                "5",
                "6",
                "7",
                "8",
                "9",
                "10",
                "11",
                "12",
                "13",
                "14",
                "15",
                "16",
                "17",
                "18",
                "19",
                "20",
                "21",
                "22",
                "X",
                "Y",
                "M",
                name="HumanGenome",
            ),
            nullable=False,
        ),
        sa.Column(
            "genomic_region", niagads.database.decorators.RangeType(), nullable=False
        ),
        sa.Column(
            "bin_index", sqlalchemy_utils.types.ltree.LtreeType(), nullable=False
        ),
        sa.CheckConstraint(
            "chromosome in ('1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', 'X', 'Y', 'M')",
            name="check_chromosome",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["admin.etlrun.etl_run_id"],
        ),
        sa.PrimaryKeyConstraint("interval_bin_id"),
        schema="reference",
    )
    op.create_index(
        "ix_reference_intervalbin__bin_index",
        "intervalbin",
        ["bin_index"],
        unique=False,
        schema="reference",
        postgresql_using="gist",
    )
    op.create_index(
        "ix_reference_intervalbin__genomic_region",
        "intervalbin",
        ["genomic_region"],
        unique=False,
        schema="reference",
        postgresql_using="gist",
    )
    op.create_index(
        op.f("ix_reference_intervalbin_chromosome"),
        "intervalbin",
        ["chromosome"],
        unique=False,
        schema="reference",
    )
    op.create_index(
        op.f("ix_reference_intervalbin_run_id"),
        "intervalbin",
        ["run_id"],
        unique=False,
        schema="reference",
    )
    op.create_table(
        "gene",
        sa.Column("gene_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("gene_symbol", sa.String(length=50), nullable=False),
        sa.Column("gene_name", sa.String(length=250), nullable=False),
        sa.Column("gene_type", sa.String(length=150), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column(
            "creation_date",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "modification_date",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("external_database_id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.String(length=50), nullable=False),
        sa.Column(
            "chromosome",
            sa.Enum(
                "1",
                "2",
                "3",
                "4",
                "5",
                "6",
                "7",
                "8",
                "9",
                "10",
                "11",
                "12",
                "13",
                "14",
                "15",
                "16",
                "17",
                "18",
                "19",
                "20",
                "21",
                "22",
                "X",
                "Y",
                "M",
                name="HumanGenome",
            ),
            nullable=False,
        ),
        sa.Column(
            "genomic_region", niagads.database.decorators.RangeType(), nullable=False
        ),
        sa.Column(
            "bin_index", sqlalchemy_utils.types.ltree.LtreeType(), nullable=False
        ),
        sa.CheckConstraint(
            "chromosome in ('1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', 'X', 'Y', 'M')",
            name="check_chromosome",
        ),
        sa.CheckConstraint(
            "source_id ~ '^ENSG\\d{11}$'", name="gene_source_id_format_check"
        ),
        sa.ForeignKeyConstraint(
            ["external_database_id"],
            ["reference.externaldatabase.external_database_id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["admin.etlrun.etl_run_id"],
        ),
        sa.PrimaryKeyConstraint("gene_id"),
        schema="gene",
    )
    op.create_index(
        "ix_gene_gene__bin_index",
        "gene",
        ["bin_index"],
        unique=False,
        schema="gene",
        postgresql_using="gist",
    )
    op.create_index(
        "ix_gene_gene__genomic_region",
        "gene",
        ["genomic_region"],
        unique=False,
        schema="gene",
        postgresql_using="gist",
    )
    op.create_index(
        op.f("ix_gene_gene_chromosome"),
        "gene",
        ["chromosome"],
        unique=False,
        schema="gene",
    )
    op.create_index(
        op.f("ix_gene_gene_external_database_id"),
        "gene",
        ["external_database_id"],
        unique=False,
        schema="gene",
    )
    op.create_index(
        op.f("ix_gene_gene_run_id"), "gene", ["run_id"], unique=False, schema="gene"
    )
    op.create_index(
        op.f("ix_gene_gene_source_id"),
        "gene",
        ["source_id"],
        unique=False,
        schema="gene",
    )
    op.create_table(
        "chunkmetadata",
        sa.Column(
            "chunk_metadata_id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("chunk_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column(
            "section", sa.String(length=64), server_default="FULL", nullable=False
        ),
        sa.Column("chunk_index", sa.Integer(), nullable=True),
        sa.Column("start_offset", sa.Integer(), nullable=True),
        sa.Column("end_offset", sa.Integer(), nullable=True),
        sa.Column("chunk_text", sa.TEXT(), nullable=True),
        sa.Column("doc_hash", sa.LargeBinary(length=32), nullable=True),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column(
            "creation_date",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "modification_date",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("table_id", sa.Integer(), nullable=False),
        sa.Column("row_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["admin.etlrun.etl_run_id"],
        ),
        sa.ForeignKeyConstraint(
            ["table_id"],
            ["admin.tablecatalog.table_id"],
        ),
        sa.PrimaryKeyConstraint("chunk_metadata_id"),
        sa.UniqueConstraint(
            "table_id",
            "row_id",
            "section",
            "chunk_index",
            "chunk_hash",
            name="uq_chunk_metadata",
        ),
        schema="ragdoc",
    )
    op.create_index(
        "ix_chunkmetadata_chunk_hash",
        "chunkmetadata",
        ["chunk_hash"],
        unique=False,
        schema="ragdoc",
    )
    op.create_index(
        "ix_chunkmetadata_table_doc",
        "chunkmetadata",
        ["table_id", "row_id"],
        unique=False,
        schema="ragdoc",
    )
    op.create_index(
        op.f("ix_ragdoc_chunkmetadata_row_id"),
        "chunkmetadata",
        ["row_id"],
        unique=False,
        schema="ragdoc",
    )
    op.create_index(
        op.f("ix_ragdoc_chunkmetadata_run_id"),
        "chunkmetadata",
        ["run_id"],
        unique=False,
        schema="ragdoc",
    )
    op.create_index(
        op.f("ix_ragdoc_chunkmetadata_table_id"),
        "chunkmetadata",
        ["table_id"],
        unique=False,
        schema="ragdoc",
    )
    op.create_table(
        "ontologyterm",
        sa.Column("ontology_term_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("term", sa.String(length=512), nullable=False),
        sa.Column("term_iri", sa.String(length=250), nullable=False),
        sa.Column(
            "entity_type",
            sa.Enum(
                "CLASS",
                "OBJECT_PROPERTY",
                "NAMED_INDIVIDUAL",
                "ANNOTATION_PROPERTY",
                name="EntityTypeIRI",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("label", sa.String(length=100), nullable=True),
        sa.Column("definition", sa.TEXT(), nullable=True),
        sa.Column("synonyms", sa.ARRAY(sa.String(length=250)), nullable=True),
        sa.Column("is_deprecated", sa.Boolean(), nullable=True),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column(
            "creation_date",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "modification_date",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("external_database_id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.String(length=50), nullable=False),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True
        ),
        sa.Column("embedding_model", sa.String(length=250), nullable=True),
        sa.Column("embedding_hash", sa.LargeBinary(length=32), nullable=True),
        sa.Column("embedding_date", sa.TIMESTAMP(), nullable=True),
        sa.Column("embedding_run_id", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "entity_type in ('CLASS', 'OBJECT_PROPERTY', 'NAMED_INDIVIDUAL', 'ANNOTATION_PROPERTY')",
            name="check_entity_type",
        ),
        sa.ForeignKeyConstraint(
            ["embedding_run_id"],
            ["admin.etlrun.etl_run_id"],
        ),
        sa.ForeignKeyConstraint(
            ["external_database_id"],
            ["reference.externaldatabase.external_database_id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["admin.etlrun.etl_run_id"],
        ),
        sa.PrimaryKeyConstraint("ontology_term_id"),
        sa.UniqueConstraint("external_database_id", "source_id"),
        sa.UniqueConstraint("source_id", name="uq_ontology_term_id"),
        schema="reference",
    )
    op.create_index(
        "ix_ontologyterm_term_trgm",
        "ontologyterm",
        ["term"],
        unique=False,
        schema="reference",
        postgresql_using="gin",
        postgresql_ops={"term": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_reference_ontologyterm_embedding",
        "ontologyterm",
        ["embedding"],
        unique=False,
        schema="reference",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        op.f("ix_reference_ontologyterm_embedding_model"),
        "ontologyterm",
        ["embedding_model"],
        unique=False,
        schema="reference",
    )
    op.create_index(
        op.f("ix_reference_ontologyterm_embedding_run_id"),
        "ontologyterm",
        ["embedding_run_id"],
        unique=False,
        schema="reference",
    )
    op.create_index(
        op.f("ix_reference_ontologyterm_entity_type"),
        "ontologyterm",
        ["entity_type"],
        unique=False,
        schema="reference",
    )
    op.create_index(
        op.f("ix_reference_ontologyterm_external_database_id"),
        "ontologyterm",
        ["external_database_id"],
        unique=False,
        schema="reference",
    )
    op.create_index(
        op.f("ix_reference_ontologyterm_run_id"),
        "ontologyterm",
        ["run_id"],
        unique=False,
        schema="reference",
    )
    op.create_index(
        op.f("ix_reference_ontologyterm_source_id"),
        "ontologyterm",
        ["source_id"],
        unique=False,
        schema="reference",
    )
    op.create_index(
        op.f("ix_reference_ontologyterm_term"),
        "ontologyterm",
        ["term"],
        unique=False,
        schema="reference",
    )
    op.create_table(
        "pathway",
        sa.Column("pathway_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(length=400), nullable=True),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column(
            "creation_date",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "modification_date",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("external_database_id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.String(length=50), nullable=False),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True
        ),
        sa.Column("embedding_model", sa.String(length=250), nullable=True),
        sa.Column("embedding_hash", sa.LargeBinary(length=32), nullable=True),
        sa.Column("embedding_date", sa.TIMESTAMP(), nullable=True),
        sa.Column("embedding_run_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["embedding_run_id"],
            ["admin.etlrun.etl_run_id"],
        ),
        sa.ForeignKeyConstraint(
            ["external_database_id"],
            ["reference.externaldatabase.external_database_id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["admin.etlrun.etl_run_id"],
        ),
        sa.PrimaryKeyConstraint("pathway_id"),
        sa.UniqueConstraint("external_database_id", "source_id"),
        schema="reference",
    )
    op.create_index(
        "ix_reference_pathway_embedding",
        "pathway",
        ["embedding"],
        unique=False,
        schema="reference",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        op.f("ix_reference_pathway_embedding_model"),
        "pathway",
        ["embedding_model"],
        unique=False,
        schema="reference",
    )
    op.create_index(
        op.f("ix_reference_pathway_embedding_run_id"),
        "pathway",
        ["embedding_run_id"],
        unique=False,
        schema="reference",
    )
    op.create_index(
        op.f("ix_reference_pathway_external_database_id"),
        "pathway",
        ["external_database_id"],
        unique=False,
        schema="reference",
    )
    op.create_index(
        op.f("ix_reference_pathway_name"),
        "pathway",
        ["name"],
        unique=False,
        schema="reference",
    )
    op.create_index(
        op.f("ix_reference_pathway_run_id"),
        "pathway",
        ["run_id"],
        unique=False,
        schema="reference",
    )
    op.create_index(
        op.f("ix_reference_pathway_source_id"),
        "pathway",
        ["source_id"],
        unique=False,
        schema="reference",
    )
    op.create_table(
        "track",
        sa.Column("track_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "data_store",
            sa.Enum(
                "GENOMICSDB",
                "FILER",
                "SHARED",
                name="TrackDataStore",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("dataset_type_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=False),
        sa.Column(
            "genome_build",
            sa.Enum("GRCh37", "GRCh38", name="Assembly", native_enum=False),
            nullable=False,
        ),
        sa.Column("feature_type", sa.String(length=50), nullable=False),
        sa.Column("is_download_only", sa.Boolean(), nullable=False),
        sa.Column("searchable_text", sa.TEXT(), nullable=False),
        sa.Column("is_shard", sa.Boolean(), nullable=True),
        sa.Column(
            "shard_chromosome",
            sa.Enum(
                "1",
                "2",
                "3",
                "4",
                "5",
                "6",
                "7",
                "8",
                "9",
                "10",
                "11",
                "12",
                "13",
                "14",
                "15",
                "16",
                "17",
                "18",
                "19",
                "20",
                "21",
                "22",
                "X",
                "Y",
                "M",
                name="HumanGenome",
            ),
            nullable=True,
        ),
        sa.Column("shard_root_track_id", sa.String(), nullable=True),
        sa.Column("cohorts", sa.ARRAY(sa.String()), nullable=True),
        sa.Column(
            "biosample_characteristics",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "participant_phenotypes",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "experimental_design",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "provenance",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "file_properties",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column(
            "creation_date",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "modification_date",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("external_database_id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.String(length=50), nullable=False),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True
        ),
        sa.Column("embedding_model", sa.String(length=250), nullable=True),
        sa.Column("embedding_hash", sa.LargeBinary(length=32), nullable=True),
        sa.Column("embedding_date", sa.TIMESTAMP(), nullable=True),
        sa.Column("embedding_run_id", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "data_store in ('GENOMICSDB', 'FILER', 'SHARED')", name="check_data_store"
        ),
        sa.CheckConstraint(
            "genome_build in ('GRCh37', 'GRCh38')", name="check_genome_build"
        ),
        sa.CheckConstraint(
            "shard_chromosome in ('1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', 'X', 'Y', 'M')",
            name="check_shard_chromosome",
        ),
        sa.ForeignKeyConstraint(
            ["dataset_type_id"],
            ["reference.ontologyterm.ontology_term_id"],
        ),
        sa.ForeignKeyConstraint(
            ["embedding_run_id"],
            ["admin.etlrun.etl_run_id"],
        ),
        sa.ForeignKeyConstraint(
            ["external_database_id"],
            ["reference.externaldatabase.external_database_id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["admin.etlrun.etl_run_id"],
        ),
        sa.PrimaryKeyConstraint("track_id"),
        sa.UniqueConstraint("external_database_id", "source_id"),
        schema="dataset",
    )
    op.create_index(
        op.f("ix_dataset_track_data_store"),
        "track",
        ["data_store"],
        unique=False,
        schema="dataset",
    )
    op.create_index(
        op.f("ix_dataset_track_dataset_type_id"),
        "track",
        ["dataset_type_id"],
        unique=False,
        schema="dataset",
    )
    op.create_index(
        "ix_dataset_track_embedding",
        "track",
        ["embedding"],
        unique=False,
        schema="dataset",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        op.f("ix_dataset_track_embedding_model"),
        "track",
        ["embedding_model"],
        unique=False,
        schema="dataset",
    )
    op.create_index(
        op.f("ix_dataset_track_embedding_run_id"),
        "track",
        ["embedding_run_id"],
        unique=False,
        schema="dataset",
    )
    op.create_index(
        op.f("ix_dataset_track_external_database_id"),
        "track",
        ["external_database_id"],
        unique=False,
        schema="dataset",
    )
    op.create_index(
        op.f("ix_dataset_track_feature_type"),
        "track",
        ["feature_type"],
        unique=False,
        schema="dataset",
    )
    op.create_index(
        op.f("ix_dataset_track_genome_build"),
        "track",
        ["genome_build"],
        unique=False,
        schema="dataset",
    )
    op.create_index(
        op.f("ix_dataset_track_is_download_only"),
        "track",
        ["is_download_only"],
        unique=False,
        schema="dataset",
    )
    op.create_index(
        op.f("ix_dataset_track_run_id"),
        "track",
        ["run_id"],
        unique=False,
        schema="dataset",
    )
    op.create_index(
        op.f("ix_dataset_track_source_id"),
        "track",
        ["source_id"],
        unique=False,
        schema="dataset",
    )
    op.create_index(
        "ix_metadata_track_searchable_text",
        "track",
        ["searchable_text"],
        unique=False,
        schema="dataset",
        postgresql_using="gin",
        postgresql_ops={"searchable_text": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_metadata_track_shard_root_track_id",
        "track",
        ["shard_root_track_id"],
        unique=False,
        schema="dataset",
        postgresql_where=sa.text("shard_root_track_id IS NOT NULL"),
    )
    op.create_table(
        "annotationevidence",
        sa.Column(
            "annotation_evidence_id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("evidence_code_id", sa.Integer(), nullable=False),
        sa.Column(
            "qualifiers",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column(
            "creation_date",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "modification_date",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("external_database_id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.String(length=50), nullable=False),
        sa.Column("table_id", sa.Integer(), nullable=False),
        sa.Column("row_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["evidence_code_id"],
            ["reference.ontologyterm.ontology_term_id"],
        ),
        sa.ForeignKeyConstraint(
            ["external_database_id"],
            ["reference.externaldatabase.external_database_id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["admin.etlrun.etl_run_id"],
        ),
        sa.ForeignKeyConstraint(
            ["table_id"],
            ["admin.tablecatalog.table_id"],
        ),
        sa.PrimaryKeyConstraint("annotation_evidence_id"),
        sa.UniqueConstraint(
            "evidence_code_id", "table_id", "row_id", name="uq_gene_annotation_evidence"
        ),
        schema="gene",
    )
    op.create_index(
        op.f("ix_gene_annotationevidence_evidence_code_id"),
        "annotationevidence",
        ["evidence_code_id"],
        unique=False,
        schema="gene",
    )
    op.create_index(
        op.f("ix_gene_annotationevidence_external_database_id"),
        "annotationevidence",
        ["external_database_id"],
        unique=False,
        schema="gene",
    )
    op.create_index(
        op.f("ix_gene_annotationevidence_row_id"),
        "annotationevidence",
        ["row_id"],
        unique=False,
        schema="gene",
    )
    op.create_index(
        op.f("ix_gene_annotationevidence_run_id"),
        "annotationevidence",
        ["run_id"],
        unique=False,
        schema="gene",
    )
    op.create_index(
        op.f("ix_gene_annotationevidence_source_id"),
        "annotationevidence",
        ["source_id"],
        unique=False,
        schema="gene",
    )
    op.create_index(
        op.f("ix_gene_annotationevidence_table_id"),
        "annotationevidence",
        ["table_id"],
        unique=False,
        schema="gene",
    )
    op.create_table(
        "goassociation",
        sa.Column(
            "go_association_id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("go_term_id", sa.Integer(), nullable=False),
        sa.Column("gene_id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column(
            "creation_date",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "modification_date",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("external_database_id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["external_database_id"],
            ["reference.externaldatabase.external_database_id"],
        ),
        sa.ForeignKeyConstraint(
            ["gene_id"],
            ["gene.gene.gene_id"],
        ),
        sa.ForeignKeyConstraint(
            ["go_term_id"],
            ["reference.ontologyterm.ontology_term_id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["admin.etlrun.etl_run_id"],
        ),
        sa.PrimaryKeyConstraint("go_association_id"),
        sa.UniqueConstraint("go_term_id", "gene_id", name="uq_go_association"),
        schema="gene",
    )
    op.create_index(
        op.f("ix_gene_goassociation_external_database_id"),
        "goassociation",
        ["external_database_id"],
        unique=False,
        schema="gene",
    )
    op.create_index(
        op.f("ix_gene_goassociation_gene_id"),
        "goassociation",
        ["gene_id"],
        unique=False,
        schema="gene",
    )
    op.create_index(
        op.f("ix_gene_goassociation_go_term_id"),
        "goassociation",
        ["go_term_id"],
        unique=False,
        schema="gene",
    )
    op.create_index(
        op.f("ix_gene_goassociation_run_id"),
        "goassociation",
        ["run_id"],
        unique=False,
        schema="gene",
    )
    op.create_index(
        op.f("ix_gene_goassociation_source_id"),
        "goassociation",
        ["source_id"],
        unique=False,
        schema="gene",
    )
    op.create_table(
        "pathwaymembership",
        sa.Column(
            "pathway_membership_id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("pathway_id", sa.Integer(), nullable=False),
        sa.Column("gene_id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column(
            "creation_date",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "modification_date",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("external_database_id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["external_database_id"],
            ["reference.externaldatabase.external_database_id"],
        ),
        sa.ForeignKeyConstraint(
            ["gene_id"],
            ["gene.gene.gene_id"],
        ),
        sa.ForeignKeyConstraint(
            ["pathway_id"],
            ["reference.pathway.pathway_id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["admin.etlrun.etl_run_id"],
        ),
        sa.PrimaryKeyConstraint("pathway_membership_id"),
        sa.UniqueConstraint("pathway_id", "gene_id", name="uq_pathway_gene_membership"),
        schema="gene",
    )
    op.create_index(
        op.f("ix_gene_pathwaymembership_external_database_id"),
        "pathwaymembership",
        ["external_database_id"],
        unique=False,
        schema="gene",
    )
    op.create_index(
        op.f("ix_gene_pathwaymembership_gene_id"),
        "pathwaymembership",
        ["gene_id"],
        unique=False,
        schema="gene",
    )
    op.create_index(
        op.f("ix_gene_pathwaymembership_pathway_id"),
        "pathwaymembership",
        ["pathway_id"],
        unique=False,
        schema="gene",
    )
    op.create_index(
        op.f("ix_gene_pathwaymembership_run_id"),
        "pathwaymembership",
        ["run_id"],
        unique=False,
        schema="gene",
    )
    op.create_index(
        op.f("ix_gene_pathwaymembership_source_id"),
        "pathwaymembership",
        ["source_id"],
        unique=False,
        schema="gene",
    )
    op.create_table(
        "transcript",
        sa.Column("transcript_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("gene_id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column(
            "creation_date",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "modification_date",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("external_database_id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.String(length=50), nullable=False),
        sa.Column(
            "chromosome",
            sa.Enum(
                "1",
                "2",
                "3",
                "4",
                "5",
                "6",
                "7",
                "8",
                "9",
                "10",
                "11",
                "12",
                "13",
                "14",
                "15",
                "16",
                "17",
                "18",
                "19",
                "20",
                "21",
                "22",
                "X",
                "Y",
                "M",
                name="HumanGenome",
            ),
            nullable=False,
        ),
        sa.Column(
            "genomic_region", niagads.database.decorators.RangeType(), nullable=False
        ),
        sa.Column(
            "bin_index", sqlalchemy_utils.types.ltree.LtreeType(), nullable=False
        ),
        sa.CheckConstraint(
            "chromosome in ('1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', 'X', 'Y', 'M')",
            name="check_chromosome",
        ),
        sa.CheckConstraint(
            "source_id ~ '^ENST\\d{11}$'", name="transcript_source_id_format_check"
        ),
        sa.ForeignKeyConstraint(
            ["external_database_id"],
            ["reference.externaldatabase.external_database_id"],
        ),
        sa.ForeignKeyConstraint(
            ["gene_id"],
            ["gene.gene.gene_id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["admin.etlrun.etl_run_id"],
        ),
        sa.PrimaryKeyConstraint("transcript_id"),
        schema="gene",
    )
    op.create_index(
        "ix_gene_transcript__bin_index",
        "transcript",
        ["bin_index"],
        unique=False,
        schema="gene",
        postgresql_using="gist",
    )
    op.create_index(
        "ix_gene_transcript__genomic_region",
        "transcript",
        ["genomic_region"],
        unique=False,
        schema="gene",
        postgresql_using="gist",
    )
    op.create_index(
        op.f("ix_gene_transcript_chromosome"),
        "transcript",
        ["chromosome"],
        unique=False,
        schema="gene",
    )
    op.create_index(
        op.f("ix_gene_transcript_external_database_id"),
        "transcript",
        ["external_database_id"],
        unique=False,
        schema="gene",
    )
    op.create_index(
        op.f("ix_gene_transcript_gene_id"),
        "transcript",
        ["gene_id"],
        unique=False,
        schema="gene",
    )
    op.create_index(
        op.f("ix_gene_transcript_run_id"),
        "transcript",
        ["run_id"],
        unique=False,
        schema="gene",
    )
    op.create_index(
        op.f("ix_gene_transcript_source_id"),
        "transcript",
        ["source_id"],
        unique=False,
        schema="gene",
    )
    op.create_table(
        "xref",
        sa.Column("xref_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("gene_id", sa.Integer(), nullable=False),
        sa.Column(
            "cross_references", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column(
            "creation_date",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "modification_date",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("external_database_id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["external_database_id"],
            ["reference.externaldatabase.external_database_id"],
        ),
        sa.ForeignKeyConstraint(
            ["gene_id"],
            ["gene.gene.gene_id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["admin.etlrun.etl_run_id"],
        ),
        sa.PrimaryKeyConstraint("xref_id"),
        sa.UniqueConstraint("external_database_id", "source_id"),
        schema="gene",
    )
    op.create_index(
        op.f("ix_gene_xref_external_database_id"),
        "xref",
        ["external_database_id"],
        unique=False,
        schema="gene",
    )
    op.create_index(
        op.f("ix_gene_xref_gene_id"), "xref", ["gene_id"], unique=False, schema="gene"
    )
    op.create_index(
        op.f("ix_gene_xref_run_id"), "xref", ["run_id"], unique=False, schema="gene"
    )
    op.create_index(
        op.f("ix_gene_xref_source_id"),
        "xref",
        ["source_id"],
        unique=False,
        schema="gene",
    )
    op.create_table(
        "chunkembedding",
        sa.Column("embedding_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("chunk_metadata_id", sa.Integer(), nullable=False),
        sa.Column("model_id", sa.String(length=100), nullable=False),
        sa.Column("chunk_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False
        ),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column(
            "creation_date",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "modification_date",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["chunk_metadata_id"],
            ["ragdoc.chunkmetadata.chunk_metadata_id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["admin.etlrun.etl_run_id"],
        ),
        sa.PrimaryKeyConstraint("embedding_id"),
        sa.UniqueConstraint(
            "chunk_metadata_id", "model_id", "chunk_hash", name="uq_embedding_chunk"
        ),
        schema="ragdoc",
    )
    op.create_index(
        "ix_chunkembedding_chunk_hash",
        "chunkembedding",
        ["chunk_hash"],
        unique=False,
        schema="ragdoc",
    )
    op.create_index(
        "ix_embedding_vector_hnsw",
        "chunkembedding",
        ["embedding"],
        unique=False,
        schema="ragdoc",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        op.f("ix_ragdoc_chunkembedding_chunk_metadata_id"),
        "chunkembedding",
        ["chunk_metadata_id"],
        unique=False,
        schema="ragdoc",
    )
    op.create_index(
        op.f("ix_ragdoc_chunkembedding_model_id"),
        "chunkembedding",
        ["model_id"],
        unique=False,
        schema="ragdoc",
    )
    op.create_index(
        op.f("ix_ragdoc_chunkembedding_run_id"),
        "chunkembedding",
        ["run_id"],
        unique=False,
        schema="ragdoc",
    )
    op.create_table(
        "trackcollectionlink",
        sa.Column(
            "track_collection_link", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("collection_id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column(
            "creation_date",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "modification_date",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["dataset.collection.collection_id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["admin.etlrun.etl_run_id"],
        ),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["dataset.track.track_id"],
        ),
        sa.PrimaryKeyConstraint("track_collection_link"),
        schema="dataset",
    )
    op.create_index(
        op.f("ix_dataset_trackcollectionlink_collection_id"),
        "trackcollectionlink",
        ["collection_id"],
        unique=False,
        schema="dataset",
    )
    op.create_index(
        op.f("ix_dataset_trackcollectionlink_run_id"),
        "trackcollectionlink",
        ["run_id"],
        unique=False,
        schema="dataset",
    )
    op.create_index(
        op.f("ix_dataset_trackcollectionlink_track_id"),
        "trackcollectionlink",
        ["track_id"],
        unique=False,
        schema="dataset",
    )
    op.create_index(
        "ix_metadata_trackcollectionlink_collection_id",
        "trackcollectionlink",
        ["collection_id"],
        unique=False,
        schema="dataset",
        postgresql_include=["track_id"],
    )
    op.create_table(
        "trackinterval",
        sa.Column(
            "track_interval_id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("num_hits", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column(
            "creation_date",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "modification_date",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "chromosome",
            sa.Enum(
                "1",
                "2",
                "3",
                "4",
                "5",
                "6",
                "7",
                "8",
                "9",
                "10",
                "11",
                "12",
                "13",
                "14",
                "15",
                "16",
                "17",
                "18",
                "19",
                "20",
                "21",
                "22",
                "X",
                "Y",
                "M",
                name="HumanGenome",
            ),
            nullable=False,
        ),
        sa.Column(
            "genomic_region", niagads.database.decorators.RangeType(), nullable=False
        ),
        sa.Column(
            "bin_index", sqlalchemy_utils.types.ltree.LtreeType(), nullable=False
        ),
        sa.CheckConstraint(
            "chromosome in ('1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', 'X', 'Y', 'M')",
            name="check_chromosome",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["admin.etlrun.etl_run_id"],
        ),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["dataset.track.track_id"],
        ),
        sa.PrimaryKeyConstraint("track_interval_id"),
        schema="dataset",
    )
    op.create_index(
        "ix_dataset_trackinterval__bin_index",
        "trackinterval",
        ["bin_index"],
        unique=False,
        schema="dataset",
        postgresql_using="gist",
    )
    op.create_index(
        "ix_dataset_trackinterval__genomic_region",
        "trackinterval",
        ["genomic_region"],
        unique=False,
        schema="dataset",
        postgresql_using="gist",
    )
    op.create_index(
        op.f("ix_dataset_trackinterval_chromosome"),
        "trackinterval",
        ["chromosome"],
        unique=False,
        schema="dataset",
    )
    op.create_index(
        op.f("ix_dataset_trackinterval_run_id"),
        "trackinterval",
        ["run_id"],
        unique=False,
        schema="dataset",
    )
    op.create_index(
        op.f("ix_dataset_trackinterval_track_id"),
        "trackinterval",
        ["track_id"],
        unique=False,
        schema="dataset",
    )
    op.create_index(
        "ix_index_trackinterval_track_id",
        "trackinterval",
        ["track_id"],
        unique=False,
        schema="dataset",
        postgresql_include=["num_hits", "genomic_region"],
    )
    op.create_table(
        "exon",
        sa.Column("exon_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("gene_id", sa.Integer(), nullable=False),
        sa.Column("transcript_id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column(
            "creation_date",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "modification_date",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("external_database_id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.String(length=50), nullable=False),
        sa.Column(
            "chromosome",
            sa.Enum(
                "1",
                "2",
                "3",
                "4",
                "5",
                "6",
                "7",
                "8",
                "9",
                "10",
                "11",
                "12",
                "13",
                "14",
                "15",
                "16",
                "17",
                "18",
                "19",
                "20",
                "21",
                "22",
                "X",
                "Y",
                "M",
                name="HumanGenome",
            ),
            nullable=False,
        ),
        sa.Column(
            "genomic_region", niagads.database.decorators.RangeType(), nullable=False
        ),
        sa.Column(
            "bin_index", sqlalchemy_utils.types.ltree.LtreeType(), nullable=False
        ),
        sa.CheckConstraint(
            "chromosome in ('1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', 'X', 'Y', 'M')",
            name="check_chromosome",
        ),
        sa.CheckConstraint(
            "source_id ~ '^ENSE\\d{11}$'", name="exon_source_id_format_check"
        ),
        sa.ForeignKeyConstraint(
            ["external_database_id"],
            ["reference.externaldatabase.external_database_id"],
        ),
        sa.ForeignKeyConstraint(
            ["gene_id"],
            ["gene.gene.gene_id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["admin.etlrun.etl_run_id"],
        ),
        sa.ForeignKeyConstraint(
            ["transcript_id"],
            ["gene.transcript.transcript_id"],
        ),
        sa.PrimaryKeyConstraint("exon_id"),
        schema="gene",
    )
    op.create_index(
        "ix_gene_exon__bin_index",
        "exon",
        ["bin_index"],
        unique=False,
        schema="gene",
        postgresql_using="gist",
    )
    op.create_index(
        "ix_gene_exon__genomic_region",
        "exon",
        ["genomic_region"],
        unique=False,
        schema="gene",
        postgresql_using="gist",
    )
    op.create_index(
        op.f("ix_gene_exon_chromosome"),
        "exon",
        ["chromosome"],
        unique=False,
        schema="gene",
    )
    op.create_index(
        op.f("ix_gene_exon_external_database_id"),
        "exon",
        ["external_database_id"],
        unique=False,
        schema="gene",
    )
    op.create_index(
        op.f("ix_gene_exon_gene_id"), "exon", ["gene_id"], unique=False, schema="gene"
    )
    op.create_index(
        op.f("ix_gene_exon_run_id"), "exon", ["run_id"], unique=False, schema="gene"
    )
    op.create_index(
        op.f("ix_gene_exon_source_id"),
        "exon",
        ["source_id"],
        unique=False,
        schema="gene",
    )
    op.create_index(
        op.f("ix_gene_exon_transcript_id"),
        "exon",
        ["transcript_id"],
        unique=False,
        schema="gene",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_gene_exon_transcript_id"), table_name="exon", schema="gene")
    op.drop_index(op.f("ix_gene_exon_source_id"), table_name="exon", schema="gene")
    op.drop_index(op.f("ix_gene_exon_run_id"), table_name="exon", schema="gene")
    op.drop_index(op.f("ix_gene_exon_gene_id"), table_name="exon", schema="gene")
    op.drop_index(
        op.f("ix_gene_exon_external_database_id"), table_name="exon", schema="gene"
    )
    op.drop_index(op.f("ix_gene_exon_chromosome"), table_name="exon", schema="gene")
    op.drop_index(
        "ix_gene_exon__genomic_region",
        table_name="exon",
        schema="gene",
        postgresql_using="gist",
    )
    op.drop_index(
        "ix_gene_exon__bin_index",
        table_name="exon",
        schema="gene",
        postgresql_using="gist",
    )
    op.drop_table("exon", schema="gene")
    op.drop_index(
        "ix_index_trackinterval_track_id",
        table_name="trackinterval",
        schema="dataset",
        postgresql_include=["num_hits", "genomic_region"],
    )
    op.drop_index(
        op.f("ix_dataset_trackinterval_track_id"),
        table_name="trackinterval",
        schema="dataset",
    )
    op.drop_index(
        op.f("ix_dataset_trackinterval_run_id"),
        table_name="trackinterval",
        schema="dataset",
    )
    op.drop_index(
        op.f("ix_dataset_trackinterval_chromosome"),
        table_name="trackinterval",
        schema="dataset",
    )
    op.drop_index(
        "ix_dataset_trackinterval__genomic_region",
        table_name="trackinterval",
        schema="dataset",
        postgresql_using="gist",
    )
    op.drop_index(
        "ix_dataset_trackinterval__bin_index",
        table_name="trackinterval",
        schema="dataset",
        postgresql_using="gist",
    )
    op.drop_table("trackinterval", schema="dataset")
    op.drop_index(
        "ix_metadata_trackcollectionlink_collection_id",
        table_name="trackcollectionlink",
        schema="dataset",
        postgresql_include=["track_id"],
    )
    op.drop_index(
        op.f("ix_dataset_trackcollectionlink_track_id"),
        table_name="trackcollectionlink",
        schema="dataset",
    )
    op.drop_index(
        op.f("ix_dataset_trackcollectionlink_run_id"),
        table_name="trackcollectionlink",
        schema="dataset",
    )
    op.drop_index(
        op.f("ix_dataset_trackcollectionlink_collection_id"),
        table_name="trackcollectionlink",
        schema="dataset",
    )
    op.drop_table("trackcollectionlink", schema="dataset")
    op.drop_index(
        op.f("ix_ragdoc_chunkembedding_run_id"),
        table_name="chunkembedding",
        schema="ragdoc",
    )
    op.drop_index(
        op.f("ix_ragdoc_chunkembedding_model_id"),
        table_name="chunkembedding",
        schema="ragdoc",
    )
    op.drop_index(
        op.f("ix_ragdoc_chunkembedding_chunk_metadata_id"),
        table_name="chunkembedding",
        schema="ragdoc",
    )
    op.drop_index(
        "ix_embedding_vector_hnsw",
        table_name="chunkembedding",
        schema="ragdoc",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_index(
        "ix_chunkembedding_chunk_hash", table_name="chunkembedding", schema="ragdoc"
    )
    op.drop_table("chunkembedding", schema="ragdoc")
    op.drop_index(op.f("ix_gene_xref_source_id"), table_name="xref", schema="gene")
    op.drop_index(op.f("ix_gene_xref_run_id"), table_name="xref", schema="gene")
    op.drop_index(op.f("ix_gene_xref_gene_id"), table_name="xref", schema="gene")
    op.drop_index(
        op.f("ix_gene_xref_external_database_id"), table_name="xref", schema="gene"
    )
    op.drop_table("xref", schema="gene")
    op.drop_index(
        op.f("ix_gene_transcript_source_id"), table_name="transcript", schema="gene"
    )
    op.drop_index(
        op.f("ix_gene_transcript_run_id"), table_name="transcript", schema="gene"
    )
    op.drop_index(
        op.f("ix_gene_transcript_gene_id"), table_name="transcript", schema="gene"
    )
    op.drop_index(
        op.f("ix_gene_transcript_external_database_id"),
        table_name="transcript",
        schema="gene",
    )
    op.drop_index(
        op.f("ix_gene_transcript_chromosome"), table_name="transcript", schema="gene"
    )
    op.drop_index(
        "ix_gene_transcript__genomic_region",
        table_name="transcript",
        schema="gene",
        postgresql_using="gist",
    )
    op.drop_index(
        "ix_gene_transcript__bin_index",
        table_name="transcript",
        schema="gene",
        postgresql_using="gist",
    )
    op.drop_table("transcript", schema="gene")
    op.drop_index(
        op.f("ix_gene_pathwaymembership_source_id"),
        table_name="pathwaymembership",
        schema="gene",
    )
    op.drop_index(
        op.f("ix_gene_pathwaymembership_run_id"),
        table_name="pathwaymembership",
        schema="gene",
    )
    op.drop_index(
        op.f("ix_gene_pathwaymembership_pathway_id"),
        table_name="pathwaymembership",
        schema="gene",
    )
    op.drop_index(
        op.f("ix_gene_pathwaymembership_gene_id"),
        table_name="pathwaymembership",
        schema="gene",
    )
    op.drop_index(
        op.f("ix_gene_pathwaymembership_external_database_id"),
        table_name="pathwaymembership",
        schema="gene",
    )
    op.drop_table("pathwaymembership", schema="gene")
    op.drop_index(
        op.f("ix_gene_goassociation_source_id"),
        table_name="goassociation",
        schema="gene",
    )
    op.drop_index(
        op.f("ix_gene_goassociation_run_id"), table_name="goassociation", schema="gene"
    )
    op.drop_index(
        op.f("ix_gene_goassociation_go_term_id"),
        table_name="goassociation",
        schema="gene",
    )
    op.drop_index(
        op.f("ix_gene_goassociation_gene_id"), table_name="goassociation", schema="gene"
    )
    op.drop_index(
        op.f("ix_gene_goassociation_external_database_id"),
        table_name="goassociation",
        schema="gene",
    )
    op.drop_table("goassociation", schema="gene")
    op.drop_index(
        op.f("ix_gene_annotationevidence_table_id"),
        table_name="annotationevidence",
        schema="gene",
    )
    op.drop_index(
        op.f("ix_gene_annotationevidence_source_id"),
        table_name="annotationevidence",
        schema="gene",
    )
    op.drop_index(
        op.f("ix_gene_annotationevidence_run_id"),
        table_name="annotationevidence",
        schema="gene",
    )
    op.drop_index(
        op.f("ix_gene_annotationevidence_row_id"),
        table_name="annotationevidence",
        schema="gene",
    )
    op.drop_index(
        op.f("ix_gene_annotationevidence_external_database_id"),
        table_name="annotationevidence",
        schema="gene",
    )
    op.drop_index(
        op.f("ix_gene_annotationevidence_evidence_code_id"),
        table_name="annotationevidence",
        schema="gene",
    )
    op.drop_table("annotationevidence", schema="gene")
    op.drop_index(
        "ix_metadata_track_shard_root_track_id",
        table_name="track",
        schema="dataset",
        postgresql_where=sa.text("shard_root_track_id IS NOT NULL"),
    )
    op.drop_index(
        "ix_metadata_track_searchable_text",
        table_name="track",
        schema="dataset",
        postgresql_using="gin",
        postgresql_ops={"searchable_text": "gin_trgm_ops"},
    )
    op.drop_index(
        op.f("ix_dataset_track_source_id"), table_name="track", schema="dataset"
    )
    op.drop_index(op.f("ix_dataset_track_run_id"), table_name="track", schema="dataset")
    op.drop_index(
        op.f("ix_dataset_track_is_download_only"), table_name="track", schema="dataset"
    )
    op.drop_index(
        op.f("ix_dataset_track_genome_build"), table_name="track", schema="dataset"
    )
    op.drop_index(
        op.f("ix_dataset_track_feature_type"), table_name="track", schema="dataset"
    )
    op.drop_index(
        op.f("ix_dataset_track_external_database_id"),
        table_name="track",
        schema="dataset",
    )
    op.drop_index(
        op.f("ix_dataset_track_embedding_run_id"), table_name="track", schema="dataset"
    )
    op.drop_index(
        op.f("ix_dataset_track_embedding_model"), table_name="track", schema="dataset"
    )
    op.drop_index(
        "ix_dataset_track_embedding",
        table_name="track",
        schema="dataset",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_index(
        op.f("ix_dataset_track_dataset_type_id"), table_name="track", schema="dataset"
    )
    op.drop_index(
        op.f("ix_dataset_track_data_store"), table_name="track", schema="dataset"
    )
    op.drop_table("track", schema="dataset")
    op.drop_index(
        op.f("ix_reference_pathway_source_id"), table_name="pathway", schema="reference"
    )
    op.drop_index(
        op.f("ix_reference_pathway_run_id"), table_name="pathway", schema="reference"
    )
    op.drop_index(
        op.f("ix_reference_pathway_name"), table_name="pathway", schema="reference"
    )
    op.drop_index(
        op.f("ix_reference_pathway_external_database_id"),
        table_name="pathway",
        schema="reference",
    )
    op.drop_index(
        op.f("ix_reference_pathway_embedding_run_id"),
        table_name="pathway",
        schema="reference",
    )
    op.drop_index(
        op.f("ix_reference_pathway_embedding_model"),
        table_name="pathway",
        schema="reference",
    )
    op.drop_index(
        "ix_reference_pathway_embedding",
        table_name="pathway",
        schema="reference",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_table("pathway", schema="reference")
    op.drop_index(
        op.f("ix_reference_ontologyterm_term"),
        table_name="ontologyterm",
        schema="reference",
    )
    op.drop_index(
        op.f("ix_reference_ontologyterm_source_id"),
        table_name="ontologyterm",
        schema="reference",
    )
    op.drop_index(
        op.f("ix_reference_ontologyterm_run_id"),
        table_name="ontologyterm",
        schema="reference",
    )
    op.drop_index(
        op.f("ix_reference_ontologyterm_external_database_id"),
        table_name="ontologyterm",
        schema="reference",
    )
    op.drop_index(
        op.f("ix_reference_ontologyterm_entity_type"),
        table_name="ontologyterm",
        schema="reference",
    )
    op.drop_index(
        op.f("ix_reference_ontologyterm_embedding_run_id"),
        table_name="ontologyterm",
        schema="reference",
    )
    op.drop_index(
        op.f("ix_reference_ontologyterm_embedding_model"),
        table_name="ontologyterm",
        schema="reference",
    )
    op.drop_index(
        "ix_reference_ontologyterm_embedding",
        table_name="ontologyterm",
        schema="reference",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_index(
        "ix_ontologyterm_term_trgm",
        table_name="ontologyterm",
        schema="reference",
        postgresql_using="gin",
        postgresql_ops={"term": "gin_trgm_ops"},
    )
    op.drop_table("ontologyterm", schema="reference")
    op.drop_index(
        op.f("ix_ragdoc_chunkmetadata_table_id"),
        table_name="chunkmetadata",
        schema="ragdoc",
    )
    op.drop_index(
        op.f("ix_ragdoc_chunkmetadata_run_id"),
        table_name="chunkmetadata",
        schema="ragdoc",
    )
    op.drop_index(
        op.f("ix_ragdoc_chunkmetadata_row_id"),
        table_name="chunkmetadata",
        schema="ragdoc",
    )
    op.drop_index(
        "ix_chunkmetadata_table_doc", table_name="chunkmetadata", schema="ragdoc"
    )
    op.drop_index(
        "ix_chunkmetadata_chunk_hash", table_name="chunkmetadata", schema="ragdoc"
    )
    op.drop_table("chunkmetadata", schema="ragdoc")
    op.drop_index(op.f("ix_gene_gene_source_id"), table_name="gene", schema="gene")
    op.drop_index(op.f("ix_gene_gene_run_id"), table_name="gene", schema="gene")
    op.drop_index(
        op.f("ix_gene_gene_external_database_id"), table_name="gene", schema="gene"
    )
    op.drop_index(op.f("ix_gene_gene_chromosome"), table_name="gene", schema="gene")
    op.drop_index(
        "ix_gene_gene__genomic_region",
        table_name="gene",
        schema="gene",
        postgresql_using="gist",
    )
    op.drop_index(
        "ix_gene_gene__bin_index",
        table_name="gene",
        schema="gene",
        postgresql_using="gist",
    )
    op.drop_table("gene", schema="gene")
    op.drop_index(
        op.f("ix_reference_intervalbin_run_id"),
        table_name="intervalbin",
        schema="reference",
    )
    op.drop_index(
        op.f("ix_reference_intervalbin_chromosome"),
        table_name="intervalbin",
        schema="reference",
    )
    op.drop_index(
        "ix_reference_intervalbin__genomic_region",
        table_name="intervalbin",
        schema="reference",
        postgresql_using="gist",
    )
    op.drop_index(
        "ix_reference_intervalbin__bin_index",
        table_name="intervalbin",
        schema="reference",
        postgresql_using="gist",
    )
    op.drop_table("intervalbin", schema="reference")
    op.drop_index(
        op.f("ix_reference_externaldatabase_run_id"),
        table_name="externaldatabase",
        schema="reference",
    )
    op.drop_index(
        op.f("ix_reference_externaldatabase_name"),
        table_name="externaldatabase",
        schema="reference",
    )
    op.drop_index(
        op.f("ix_reference_externaldatabase_database_key"),
        table_name="externaldatabase",
        schema="reference",
    )
    op.drop_table("externaldatabase", schema="reference")
    op.drop_index(
        "ix_metadata_collection_key_unique", table_name="collection", schema="dataset"
    )
    op.drop_index(
        "ix_metadata_collection_data_store",
        table_name="collection",
        schema="dataset",
        postgresql_include=["name", "description", "tracks_are_sharded"],
    )
    op.drop_index(
        op.f("ix_dataset_collection_run_id"), table_name="collection", schema="dataset"
    )
    op.drop_index(
        op.f("ix_dataset_collection_data_store"),
        table_name="collection",
        schema="dataset",
    )
    op.drop_table("collection", schema="dataset")
    op.drop_index(
        op.f("ix_admin_tablecatalog_schema_id"),
        table_name="tablecatalog",
        schema="admin",
    )
    op.drop_index(
        op.f("ix_admin_tablecatalog_name"), table_name="tablecatalog", schema="admin"
    )
    op.drop_table("tablecatalog", schema="admin")
    op.drop_index(
        op.f("ix_admin_schemacatalog_name"), table_name="schemacatalog", schema="admin"
    )
    op.drop_table("schemacatalog", schema="admin")
    op.drop_index(op.f("ix_admin_etlrun_status"), table_name="etlrun", schema="admin")
    op.drop_index(op.f("ix_admin_etlrun_run_id"), table_name="etlrun", schema="admin")
    op.drop_index(
        op.f("ix_admin_etlrun_operation"), table_name="etlrun", schema="admin"
    )
    op.drop_table("etlrun", schema="admin")
    # ### end Alembic commands ###
