""" "add proteinxref table"

Revision ID: b6cb6e6eb91e
Revises: f1c4bfcb7127
Create Date: 2026-05-05 15:36:05.616093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import niagads.database.decorators
import pgvector.sqlalchemy.vector
import sqlalchemy_utils.types.ltree

# revision identifiers, used by Alembic.
revision: str = 'b6cb6e6eb91e'
down_revision: Union[str, None] = 'f1c4bfcb7127'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proteinxref',
    sa.Column('protein_xref_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('protein_id', sa.Integer(), nullable=False),
    sa.Column('xref_category', sa.Enum('IDENTIFIER', 'NOMENCLATURE', 'LOCUS', 'PUBLICATION', 'RESOURCE_LINK', 'CLASSIFICATION', 'GROUP_MEMBERSHIP', 'ORTHOLOG', name='xrefcategory', native_enum=False), nullable=False),
    sa.Column('xref_label', sa.String(length=50), nullable=True),
    sa.Column('xref_value', sa.String(length=250), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('creation_date', niagads.database.decorators.AutoDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modification_date', niagads.database.decorators.AutoDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('external_database_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=50), nullable=False),
    sa.CheckConstraint("xref_category in ('IDENTIFIER', 'NOMENCLATURE', 'LOCUS', 'PUBLICATION', 'RESOURCE_LINK', 'CLASSIFICATION', 'GROUP_MEMBERSHIP', 'ORTHOLOG')", name='check_xref_category'),
    sa.ForeignKeyConstraint(['external_database_id'], ['reference.externaldatabase.external_database_id'], ),
    sa.ForeignKeyConstraint(['protein_id'], ['gene.protein.protein_id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['admin.etlrun.etl_run_id'], ),
    sa.PrimaryKeyConstraint('protein_xref_id'),
    schema='gene'
    )
    op.create_index(op.f('ix_gene_proteinxref_external_database_id'), 'proteinxref', ['external_database_id'], unique=False, schema='gene')
    op.create_index(op.f('ix_gene_proteinxref_protein_id'), 'proteinxref', ['protein_id'], unique=False, schema='gene')
    op.create_index(op.f('ix_gene_proteinxref_run_id'), 'proteinxref', ['run_id'], unique=False, schema='gene')
    op.create_index(op.f('ix_gene_proteinxref_source_id'), 'proteinxref', ['source_id'], unique=False, schema='gene')
    op.create_index(op.f('ix_gene_proteinxref_xref_category'), 'proteinxref', ['xref_category'], unique=False, schema='gene')
    op.create_index(op.f('ix_gene_proteinxref_xref_label'), 'proteinxref', ['xref_label'], unique=False, schema='gene')
    op.create_index(op.f('ix_gene_proteinxref_xref_value'), 'proteinxref', ['xref_value'], unique=False, schema='gene')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gene_proteinxref_xref_value'), table_name='proteinxref', schema='gene')
    op.drop_index(op.f('ix_gene_proteinxref_xref_label'), table_name='proteinxref', schema='gene')
    op.drop_index(op.f('ix_gene_proteinxref_xref_category'), table_name='proteinxref', schema='gene')
    op.drop_index(op.f('ix_gene_proteinxref_source_id'), table_name='proteinxref', schema='gene')
    op.drop_index(op.f('ix_gene_proteinxref_run_id'), table_name='proteinxref', schema='gene')
    op.drop_index(op.f('ix_gene_proteinxref_protein_id'), table_name='proteinxref', schema='gene')
    op.drop_index(op.f('ix_gene_proteinxref_external_database_id'), table_name='proteinxref', schema='gene')
    op.drop_table('proteinxref', schema='gene')
    # ### end Alembic commands ###
