""" "add gene list table"

Revision ID: bc48b248ceb0
Revises: c6ce923672fe
Create Date: 2026-05-27 11:23:57.062084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import niagads.database.decorators
import pgvector.sqlalchemy.vector
import sqlalchemy_utils.types.ltree

# revision identifiers, used by Alembic.
revision: str = 'bc48b248ceb0'
down_revision: Union[str, None] = 'c6ce923672fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genelistentry',
    sa.Column('gene_list_entry_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gene_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.INTEGER(), nullable=True),
    sa.Column('rank', sa.INTEGER(), nullable=True),
    sa.Column('external_database_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('creation_date', niagads.database.decorators.AutoDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modification_date', niagads.database.decorators.AutoDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['external_database_id'], ['reference.externaldatabase.external_database_id'], ),
    sa.ForeignKeyConstraint(['gene_id'], ['gene.gene.gene_id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['admin.etlrun.etl_run_id'], ),
    sa.PrimaryKeyConstraint('gene_list_entry_id'),
    sa.UniqueConstraint('external_database_id', 'gene_id', name='uq_gene_list_entry'),
    schema='gene'
    )
    op.create_index(op.f('ix_gene_genelistentry_external_database_id'), 'genelistentry', ['external_database_id'], unique=False, schema='gene')
    op.create_index(op.f('ix_gene_genelistentry_gene_id'), 'genelistentry', ['gene_id'], unique=False, schema='gene')
    op.create_index(op.f('ix_gene_genelistentry_run_id'), 'genelistentry', ['run_id'], unique=False, schema='gene')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gene_genelistentry_run_id'), table_name='genelistentry', schema='gene')
    op.drop_index(op.f('ix_gene_genelistentry_gene_id'), table_name='genelistentry', schema='gene')
    op.drop_index(op.f('ix_gene_genelistentry_external_database_id'), table_name='genelistentry', schema='gene')
    op.drop_table('genelistentry', schema='gene')
    # ### end Alembic commands ###
