""" "make is_download_only nullable"

Revision ID: c3269683f796
Revises: 714bb87b2e07
Create Date: 2026-05-16 19:20:05.324121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import niagads.database.decorators
import pgvector.sqlalchemy.vector
import sqlalchemy_utils.types.ltree

# revision identifiers, used by Alembic.
revision: str = 'c3269683f796'
down_revision: Union[str, None] = '714bb87b2e07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('track', 'is_download_only',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               schema='dataset')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('track', 'is_download_only',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               schema='dataset')
    # ### end Alembic commands ###
