""" "add missing curation_event field"

Revision ID: cb580284cda9
Revises: 5e374acb63e8
Create Date: 2026-05-15 15:22:14.561217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import niagads.database.decorators
import pgvector.sqlalchemy.vector
import sqlalchemy_utils.types.ltree

# revision identifiers, used by Alembic.
revision: str = 'cb580284cda9'
down_revision: Union[str, None] = '5e374acb63e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track', sa.Column('curation_history', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True), schema='dataset')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track', 'curation_history', schema='dataset')
    # ### end Alembic commands ###
