""" "adjust term label length"

Revision ID: d5f293771db3
Revises: 316c03b524f6
Create Date: 2026-03-27 01:57:45.272632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import niagads.database.decorators
import pgvector.sqlalchemy.vector
import sqlalchemy_utils.types.ltree

# revision identifiers, used by Alembic.
revision: str = 'd5f293771db3'
down_revision: Union[str, None] = '316c03b524f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chunkmetadata', 'chunk_index',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='ragdoc')
    op.alter_column('ontologyterm', 'label',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=512),
               existing_nullable=True,
               schema='reference')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ontologyterm', 'label',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True,
               schema='reference')
    op.alter_column('chunkmetadata', 'chunk_index',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='ragdoc')
    # ### end Alembic commands ###
