""" "remove redundant embedding_hash column"

Revision ID: dec651b22379
Revises: 534a515922f4
Create Date: 2026-03-25 05:28:15.294348

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import niagads.database.decorators
import pgvector.sqlalchemy.vector
import sqlalchemy_utils.types.ltree

# revision identifiers, used by Alembic.
revision: str = "dec651b22379"
down_revision: Union[str, None] = "534a515922f4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chunkembedding", "embedding_hash", schema="ragdoc")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chunkembedding",
        sa.Column(
            "embedding_hash", postgresql.BYTEA(), autoincrement=False, nullable=True
        ),
        schema="ragdoc",
    )
    # ### end Alembic commands ###
