""" "add missing release date"

Revision ID: e19f10fad55e
Revises: 7d80ca04cf3b
Create Date: 2026-03-12 09:10:29.846348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import niagads.database.decorators
import pgvector.sqlalchemy.vector
import sqlalchemy_utils.types.ltree

# revision identifiers, used by Alembic.
revision: str = 'e19f10fad55e'
down_revision: Union[str, None] = '7d80ca04cf3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('externaldatabase', sa.Column('release_date', sa.TIMESTAMP(), nullable=True), schema='reference')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('externaldatabase', 'release_date', schema='reference')
    # ### end Alembic commands ###
