""" "make mergehistory in refsnpalias nullable"

Revision ID: ea5d9565c7d1
Revises: f33f2356a6c9
Create Date: 2026-05-12 07:30:15.092360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import niagads.database.decorators
import pgvector.sqlalchemy.vector
import sqlalchemy_utils.types.ltree

# revision identifiers, used by Alembic.
revision: str = 'ea5d9565c7d1'
down_revision: Union[str, None] = 'f33f2356a6c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refsnpalias', 'merge_history',
               existing_type=postgresql.BYTEA(),
               nullable=True,
               schema='variant')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refsnpalias', 'merge_history',
               existing_type=postgresql.BYTEA(),
               nullable=False,
               schema='variant')
    # ### end Alembic commands ###
