""" "replace parent_id with namespace (for go) in ontologyterm"

Revision ID: eb36b45da115
Revises: f8b027f2abb0
Create Date: 2026-04-09 18:07:15.573271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import niagads.database.decorators
import pgvector.sqlalchemy.vector
import sqlalchemy_utils.types.ltree

# revision identifiers, used by Alembic.
revision: str = 'eb36b45da115'
down_revision: Union[str, None] = 'f8b027f2abb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ontologyterm', sa.Column('namespace', sa.String(length=50), nullable=True), schema='reference')
    op.drop_index('ix_reference_ontologyterm_parent_id', table_name='ontologyterm', schema='reference')
    op.create_index(op.f('ix_reference_ontologyterm_namespace'), 'ontologyterm', ['namespace'], unique=False, schema='reference')
    op.drop_constraint('ontologyterm_parent_id_fkey', 'ontologyterm', schema='reference', type_='foreignkey')
    op.drop_column('ontologyterm', 'parent_id', schema='reference')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ontologyterm', sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True), schema='reference')
    op.create_foreign_key('ontologyterm_parent_id_fkey', 'ontologyterm', 'ontologyterm', ['parent_id'], ['ontology_term_id'], source_schema='reference', referent_schema='reference')
    op.drop_index(op.f('ix_reference_ontologyterm_namespace'), table_name='ontologyterm', schema='reference')
    op.create_index('ix_reference_ontologyterm_parent_id', 'ontologyterm', ['parent_id'], unique=False, schema='reference')
    op.drop_column('ontologyterm', 'namespace', schema='reference')
    # ### end Alembic commands ###
