""" "remove source_id from pathwaymembership"

Revision ID: ec7d5289aaac
Revises: eb36b45da115
Create Date: 2026-04-14 09:52:38.881375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import niagads.database.decorators
import pgvector.sqlalchemy.vector
import sqlalchemy_utils.types.ltree

# revision identifiers, used by Alembic.
revision: str = 'ec7d5289aaac'
down_revision: Union[str, None] = 'eb36b45da115'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_gene_pathwaymembership_source_id', table_name='pathwaymembership', schema='gene')
    op.drop_column('pathwaymembership', 'source_id', schema='gene')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pathwaymembership', sa.Column('source_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False), schema='gene')
    op.create_index('ix_gene_pathwaymembership_source_id', 'pathwaymembership', ['source_id'], unique=False, schema='gene')
    # ### end Alembic commands ###
