""" "add protein table"

Revision ID: f1c4bfcb7127
Revises: 23770b2f34a2
Create Date: 2026-05-05 09:39:27.894684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import niagads.database.decorators
import pgvector.sqlalchemy.vector
import sqlalchemy_utils.types.ltree

# revision identifiers, used by Alembic.
revision: str = 'f1c4bfcb7127'
down_revision: Union[str, None] = '23770b2f34a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('protein',
    sa.Column('protein_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transcript_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('creation_date', niagads.database.decorators.AutoDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modification_date', niagads.database.decorators.AutoDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('external_database_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=50), nullable=False),
    sa.CheckConstraint("source_id ~ '^ENSP\\d+$'", name='protein_source_id_format_check'),
    sa.ForeignKeyConstraint(['external_database_id'], ['reference.externaldatabase.external_database_id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['admin.etlrun.etl_run_id'], ),
    sa.ForeignKeyConstraint(['transcript_id'], ['gene.transcript.transcript_id'], ),
    sa.PrimaryKeyConstraint('protein_id'),
    schema='gene'
    )
    op.create_index(op.f('ix_gene_protein_external_database_id'), 'protein', ['external_database_id'], unique=False, schema='gene')
    op.create_index(op.f('ix_gene_protein_run_id'), 'protein', ['run_id'], unique=False, schema='gene')
    op.create_index(op.f('ix_gene_protein_source_id'), 'protein', ['source_id'], unique=False, schema='gene')
    op.create_index(op.f('ix_gene_protein_transcript_id'), 'protein', ['transcript_id'], unique=False, schema='gene')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gene_protein_transcript_id'), table_name='protein', schema='gene')
    op.drop_index(op.f('ix_gene_protein_source_id'), table_name='protein', schema='gene')
    op.drop_index(op.f('ix_gene_protein_run_id'), table_name='protein', schema='gene')
    op.drop_index(op.f('ix_gene_protein_external_database_id'), table_name='protein', schema='gene')
    op.drop_table('protein', schema='gene')
    # ### end Alembic commands ###
