""" "modified refsnpmerge table"

Revision ID: f33f2356a6c9
Revises: 8b0e7273166f
Create Date: 2026-05-12 07:15:14.912020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import niagads.database.decorators
import pgvector.sqlalchemy.vector
import sqlalchemy_utils.types.ltree

# revision identifiers, used by Alembic.
revision: str = 'f33f2356a6c9'
down_revision: Union[str, None] = '8b0e7273166f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refsnpalias',
    sa.Column('ref_snp_alias_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_database_id', sa.Integer(), nullable=False),
    sa.Column('ref_snp_id', sa.String(length=25), nullable=False),
    sa.Column('merge_history', niagads.database.decorators.CompressedJson(), nullable=False),
    sa.Column('merged_into', sa.String(length=25), nullable=False),
    sa.Column('merge_build', sa.INTEGER(), nullable=False),
    sa.Column('merge_date', niagads.database.decorators.AutoDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('creation_date', niagads.database.decorators.AutoDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modification_date', niagads.database.decorators.AutoDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['external_database_id'], ['reference.externaldatabase.external_database_id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['admin.etlrun.etl_run_id'], ),
    sa.PrimaryKeyConstraint('ref_snp_alias_id'),
    schema='variant'
    )
    op.create_index('ix_refsnpalias_ref_snp_id', 'refsnpalias', ['ref_snp_id'], unique=False, schema='variant', postgresql_include=['merged_into', 'merge_build'])
    op.create_index(op.f('ix_variant_refsnpalias_run_id'), 'refsnpalias', ['run_id'], unique=False, schema='variant')
    op.drop_index('ix_variant_ref_snp_alias_merged_into', table_name='ref_snp_alias', schema='variant')
    op.drop_index('ix_variant_ref_snp_alias_ref_snp_id', table_name='ref_snp_alias', schema='variant')
    op.drop_index('ix_variant_ref_snp_alias_run_id', table_name='ref_snp_alias', schema='variant')
    op.drop_table('ref_snp_alias', schema='variant')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ref_snp_alias',
    sa.Column('ref_snp_alias_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ref_snp_id', sa.VARCHAR(length=25), autoincrement=False, nullable=False),
    sa.Column('merge_build', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('merge_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('run_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('creation_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('modification_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('merged_into', sa.VARCHAR(length=25), autoincrement=False, nullable=False),
    sa.Column('external_database_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['external_database_id'], ['reference.externaldatabase.external_database_id'], name='ref_snp_alias_external_database_id_fkey'),
    sa.ForeignKeyConstraint(['run_id'], ['admin.etlrun.etl_run_id'], name='ref_snp_alias_run_id_fkey'),
    sa.PrimaryKeyConstraint('ref_snp_alias_id', name='ref_snp_alias_pkey'),
    schema='variant'
    )
    op.create_index('ix_variant_ref_snp_alias_run_id', 'ref_snp_alias', ['run_id'], unique=False, schema='variant')
    op.create_index('ix_variant_ref_snp_alias_ref_snp_id', 'ref_snp_alias', ['ref_snp_id'], unique=False, schema='variant')
    op.create_index('ix_variant_ref_snp_alias_merged_into', 'ref_snp_alias', ['merged_into'], unique=False, schema='variant')
    op.drop_index(op.f('ix_variant_refsnpalias_run_id'), table_name='refsnpalias', schema='variant')
    op.drop_index('ix_refsnpalias_ref_snp_id', table_name='refsnpalias', schema='variant', postgresql_include=['merged_into', 'merge_build'])
    op.drop_table('refsnpalias', schema='variant')
    # ### end Alembic commands ###
