"""add span column; fix bin_index index name

Revision ID: f3c18d4f7ce6
Revises: 380bbd3b1ca8
Create Date: 2025-06-24 17:48:47.913801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3c18d4f7ce6'
down_revision: Union[str, None] = '380bbd3b1ca8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasetinterval', sa.Column('span', postgresql.INT8RANGE(), nullable=False), schema='index')
    op.drop_index('ix_index_bin_index', table_name='datasetinterval', schema='index', postgresql_using='gist')
    op.create_index('ix_index_datasetinterval_bin_index', 'datasetinterval', ['bin_index'], unique=False, schema='index', postgresql_using='gist')
    op.create_index('ix_index_datasetinterval_span', 'datasetinterval', ['track_id', 'span'], unique=False, schema='index', postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_index_datasetinterval_span', table_name='datasetinterval', schema='index', postgresql_using='gist')
    op.drop_index('ix_index_datasetinterval_bin_index', table_name='datasetinterval', schema='index', postgresql_using='gist')
    op.create_index('ix_index_bin_index', 'datasetinterval', ['bin_index'], unique=False, schema='index', postgresql_using='gist')
    op.drop_column('datasetinterval', 'span', schema='index')
    # ### end Alembic commands ###
