""" "missing track_ids"

Revision ID: f7cc59350c59
Revises: 7fd3ad2f135b
Create Date: 2026-09-28 09:46:06.163195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import niagads.database.decorators
import pgvector.sqlalchemy.vector
import sqlalchemy_utils.types.ltree

# revision identifiers, used by Alembic.
revision: str = 'f7cc59350c59'
down_revision: Union[str, None] = '7fd3ad2f135b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trackcollectionlink', sa.Column('track_collection_link_id', sa.Integer(), autoincrement=True, nullable=False), schema='dataset')
    op.drop_column('trackcollectionlink', 'track_collection_link', schema='dataset')
    op.add_column('trackconcept', sa.Column('track_id', sa.Integer(), nullable=False), schema='dataset')
    op.create_index(op.f('ix_dataset_trackconcept_track_id'), 'trackconcept', ['track_id'], unique=False, schema='dataset')
    op.create_foreign_key(None, 'trackconcept', 'track', ['track_id'], ['track_id'], source_schema='dataset', referent_schema='dataset')
    op.add_column('trackcontext', sa.Column('track_id', sa.Integer(), nullable=False), schema='dataset')
    op.create_index(op.f('ix_dataset_trackcontext_track_id'), 'trackcontext', ['track_id'], unique=False, schema='dataset')
    op.create_foreign_key(None, 'trackcontext', 'track', ['track_id'], ['track_id'], source_schema='dataset', referent_schema='dataset')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trackcontext', schema='dataset', type_='foreignkey')
    op.drop_index(op.f('ix_dataset_trackcontext_track_id'), table_name='trackcontext', schema='dataset')
    op.drop_column('trackcontext', 'track_id', schema='dataset')
    op.drop_constraint(None, 'trackconcept', schema='dataset', type_='foreignkey')
    op.drop_index(op.f('ix_dataset_trackconcept_track_id'), table_name='trackconcept', schema='dataset')
    op.drop_column('trackconcept', 'track_id', schema='dataset')
    op.add_column('trackcollectionlink', sa.Column('track_collection_link', sa.INTEGER(), autoincrement=True, nullable=False), schema='dataset')
    op.drop_column('trackcollectionlink', 'track_collection_link_id', schema='dataset')
    # ### end Alembic commands ###
