""" "add parent to ontology term"

- also includes changes since prior revision was lost due to tree conflict in repo

Revision ID: f8b027f2abb0
Revises: 420ad450f741
Create Date: 2026-04-09 17:55:50.789136

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import niagads.database.decorators
import pgvector.sqlalchemy.vector
import sqlalchemy_utils.types.ltree

# revision identifiers, used by Alembic.
revision: str = "f8b027f2abb0"
down_revision: Union[str, None] = "420ad450f741"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_index_trackinterval_track_id",
        "trackinterval",
        ["track_id"],
        unique=False,
        schema="dataset",
        postgresql_include=["num_hits", "span"],
    )
    op.drop_index("ix_gene_gene_gene_symbol", table_name="gene", schema="gene")
    op.alter_column(
        "xref",
        "xref_label",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
        schema="gene",
    )
    op.add_column(
        "ontologyterm",
        sa.Column("parent_id", sa.Integer(), nullable=True),
        schema="reference",
    )
    op.create_index(
        op.f("ix_reference_ontologyterm_parent_id"),
        "ontologyterm",
        ["parent_id"],
        unique=False,
        schema="reference",
    )
    op.create_foreign_key(
        None,
        "ontologyterm",
        "ontologyterm",
        ["parent_id"],
        ["ontology_term_id"],
        source_schema="reference",
        referent_schema="reference",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "ontologyterm", schema="reference", type_="foreignkey")
    op.drop_index(
        op.f("ix_reference_ontologyterm_parent_id"),
        table_name="ontologyterm",
        schema="reference",
    )
    op.drop_column("ontologyterm", "parent_id", schema="reference")
    op.alter_column(
        "xref",
        "xref_label",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
        schema="gene",
    )
    op.create_index(
        "ix_gene_gene_gene_symbol", "gene", ["gene_symbol"], unique=False, schema="gene"
    )
    op.drop_index(
        "ix_index_trackinterval_track_id",
        table_name="trackinterval",
        schema="dataset",
        postgresql_include=["num_hits", "span"],
    )
    # ### end Alembic commands ###
