""" "rename merged refsnp column"

Revision ID: fc52f3adf778
Revises: 9fc415e7b82c
Create Date: 2026-05-11 18:17:12.720891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import niagads.database.decorators
import pgvector.sqlalchemy.vector
import sqlalchemy_utils.types.ltree

# revision identifiers, used by Alembic.
revision: str = 'fc52f3adf778'
down_revision: Union[str, None] = '9fc415e7b82c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ref_snp_alias', sa.Column('merged_into', sa.String(length=25), nullable=False), schema='variant')
    op.drop_index('ix_variant_ref_snp_alias_merged_ref_snp_id', table_name='ref_snp_alias', schema='variant')
    op.create_index(op.f('ix_variant_ref_snp_alias_merged_into'), 'ref_snp_alias', ['merged_into'], unique=False, schema='variant')
    op.drop_column('ref_snp_alias', 'merged_ref_snp_id', schema='variant')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ref_snp_alias', sa.Column('merged_ref_snp_id', sa.VARCHAR(length=25), autoincrement=False, nullable=False), schema='variant')
    op.drop_index(op.f('ix_variant_ref_snp_alias_merged_into'), table_name='ref_snp_alias', schema='variant')
    op.create_index('ix_variant_ref_snp_alias_merged_ref_snp_id', 'ref_snp_alias', ['merged_ref_snp_id'], unique=False, schema='variant')
    op.drop_column('ref_snp_alias', 'merged_into', schema='variant')
    # ### end Alembic commands ###
