""" "recreate chunkembedding table-missing pk column"

Revision ID: fe5af73ec715
Revises: dec651b22379
Create Date: 2026-03-25 18:43:03.353799

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import niagads.database.decorators
import pgvector.sqlalchemy.vector
import sqlalchemy_utils.types.ltree

# revision identifiers, used by Alembic.
revision: str = "fe5af73ec715"
down_revision: Union[str, None] = "dec651b22379"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('chunkembedding', schema="ragdoc") - dropped first before creating
    op.create_table(
        "chunkembedding",
        sa.Column(
            "chunk_embedding_id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("chunk_metadata_id", sa.Integer(), nullable=False),
        sa.Column("chunk_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column(
            "creation_date",
            niagads.database.decorators.AutoDateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "modification_date",
            niagads.database.decorators.AutoDateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True
        ),
        sa.Column("embedding_model", sa.String(length=250), nullable=True),
        sa.Column(
            "embedding_date", niagads.database.decorators.AutoDateTime(), nullable=True
        ),
        sa.Column("embedding_run_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["chunk_metadata_id"],
            ["ragdoc.chunkmetadata.chunk_metadata_id"],
        ),
        sa.ForeignKeyConstraint(
            ["embedding_run_id"],
            ["admin.etlrun.etl_run_id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["admin.etlrun.etl_run_id"],
        ),
        sa.PrimaryKeyConstraint("chunk_embedding_id"),
        sa.UniqueConstraint(
            "chunk_metadata_id",
            "embedding_model",
            "chunk_hash",
            name="uq_embedding_chunk",
        ),
        schema="ragdoc",
    )
    op.create_index(
        "ix_chunkembedding_chunk_hash",
        "chunkembedding",
        ["chunk_hash"],
        unique=False,
        schema="ragdoc",
    )
    op.create_index(
        op.f("ix_ragdoc_chunkembedding_chunk_metadata_id"),
        "chunkembedding",
        ["chunk_metadata_id"],
        unique=False,
        schema="ragdoc",
    )
    op.create_index(
        "ix_ragdoc_chunkembedding_embedding",
        "chunkembedding",
        ["embedding"],
        unique=False,
        schema="ragdoc",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        op.f("ix_ragdoc_chunkembedding_embedding_model"),
        "chunkembedding",
        ["embedding_model"],
        unique=False,
        schema="ragdoc",
    )
    op.create_index(
        op.f("ix_ragdoc_chunkembedding_embedding_run_id"),
        "chunkembedding",
        ["embedding_run_id"],
        unique=False,
        schema="ragdoc",
    )
    op.create_index(
        op.f("ix_ragdoc_chunkembedding_run_id"),
        "chunkembedding",
        ["run_id"],
        unique=False,
        schema="ragdoc",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # no real downgrade b/c hopefully this is a one-off bug; initial generation did not create the PK column as serial, PK constraint
    # ### end Alembic commands ###
