"""
CREATE TABLE NIAGADS.MergedVariant  (
       MERGED_VARIANT_ID	SERIAL PRIMARY KEY,
       REF_SNP_ID		CHARACTER VARYING(25) NOT NULL,
       MERGE_REF_SNP_ID		CHARACTER VARYING(25) NOT NULL,
       MERGE_VARIANT_ID		NUMERIC(12),
       MERGE_BUILD		INTEGER NOT NULL,
       MERGE_DATE		DATE NOT NULL,
"""
