# adapted from https://github.com/ga4gh/vrs-python/blob/e28852f9369f74e07e23e4652695eb95710798f3/docker-compose.yml
services:
  seqrepo:
    container_name: gdb-seqrepo
    image: biocommons/seqrepo:2024-12-20
    volumes:
      - ${HOST_SEQREPO_DATA_DIR}:/usr/local/share/seqrepo

  seqrepo-rest-service:
    container_name: gdb-seqrepo-rest
    image: biocommons/seqrepo-rest-service:0.2.2
    volumes:
      - ${HOST_SEQREPO_DATA_DIR}:/usr/local/share/seqrepo
    depends_on:
      - seqrepo
    command: seqrepo-rest-service -w /usr/local/share/seqrepo/2024-12-20
    network_mode: bridge
    ports:
      - ${HOST_SEQREPO_SERVICE_PORT}:5000
    read_only: true

  uta:
    container_name: gdb-uta
    image: biocommons/uta:uta_20241220
    environment:
      - POSTGRES_PASSWORD=${UTA_PGADMIN_PWD}
    volumes:
      - ${HOST_UTA_DATA_DIR}:/var/lib/postgresql/data
    ports:
      - ${HOST_UTA_SERVICE_PORT}:5432

  vep:
    container_name: gdb-vep
    image: ensemblorg/ensembl-vep:${VEP_VERSION}
    environment:
      - HOME=/opt/vep
      - VEP_SRC=/opt/vep/src/ensembl-vep
      - TARGET_SPECIES=${SPECIES}
      - TARGET_ASSEMBLY=${ASSEMBLY}
      - PLUGINS=${VEP_PLUGINS}
    volumes:
      - ${HOST_VEP_CACHE_DIR}:/data:z
    entrypoint: /bin/bash -c ' if [ "$$MODE" = "install" ]; then echo "Starting Install for $$TARGET_SPECIES ($$TARGET_ASSEMBLY)..."; perl $$VEP_SRC/INSTALL.pl -a cf -s $$TARGET_SPECIES -y $$TARGET_ASSEMBLY --plugins $$PLUGINS; else $$VEP_SRC/vep "$$@"; fi'
