services:
  ragdoc-admin:
    image: ragdoc-admin
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        WHEEL: "ragdoc_admin_service-0.1.0-py3-none-any.whl"
    environment:
      DATABASE_URI: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@ragdoc-db:5432/${POSTGRES_DB}
    ports:
      - ${HOST_ADMIN_PORT}:8501
    networks:
      - shared-net
