-- table for variants
DROP TABLE IF EXISTS Variant.Variant CASCADE;

/* worth embedding 
functional_consequence
gene_context
regulatory_annotation
clinical_significance
literature_summary
pathway / ontology terms
*/

CREATE TYPE VARIANT_CLASS AS ENUM (
    'SNV',
    'MNV',
    'SHORT_INDEL',
    'SHORT_DEL',
    'SHORT_INS',
    'INDEL',
    'DEL',
    'INS',
    'DUP',
    'INV',
    'TRANS',
    'CNV',
    'MEI',
    'SV'
);

CREATE TABLE Variant.Variant (
    VARIANT_ID SERIAL PRIMARY KEY,
    CHROMOSOME HumanGenome NOT NULL,
    POSITION INTEGER NOT NULL,
    SPAN INT4RANGE NOT NULL,
    REF_ALLELE TEXT,
    ALT_ALLELE TEXT,
    DISPLAY_ALLELE TEXT,
    LENGTH INTEGER NOT NULL,
    BIN_INDEX LTREE NOT NULL,

    POSITIONAL_ID CHARACTER VARYING(150) NOT NULL,
    REF_SNP_ID CHARACTER VARYING(25),
    GA4GH_VRS JSONB NOT NULL,
    HGVS TEXT,

    TYPE VARIANT_CLASS NOT NULL,
    IS_ADSP_VARIANT BOOLEAN,
    IS_STRUCTURAL_VARIANT BOOLEAN,
    IS_ANNOTATED BOOLEAN,

    LD_PARTNERS BYTEA,

    ADSP_ANNOTATION JSONB, --QC, FAVOR, ADSP MSC
    MOST_SEVERE_CONSEQUNCE JSONB,
    FUNCTIONAL_ANNOTATION JSONB, -- vep, etc
    GWAS_ANNOTATION JSONB,
    ALLELE_FREQUENCY JSONB,
  
    -- AI generated summary + embeddings
    FUNCTIONAL_ANNOTATION_SUMMARY JSONB, 
    EMBEDDING_HASH BYTEA,
    EMBEDDING VECTOR(384),
    EMBEDDING_RUN_ID INTEGER,

    -- housekeeping
    RUN_ID INTEGER NOT NULL,
    CREATION_DATE DATE,
    MODIFICATION_DATE DATE,
    FOREIGN KEY (RUN_ID) REFERENCES Admin.ETLRun(ETL_RUN_ID),
    FOREIGN KEY (EMBEDDING_RUN_ID) REFERENCES Admin.ETLRun(ETL_RUN_ID),
) PARTITION BY LIST (CHROMOSOME);


SELECT variant.create_variant_partitions("variant.variant");

-- LOOKUP INDEXES
CREATE INDEX IX_VARIANT_VARIANT__POSITIONAL_ID ON Variant.Variant USING HASH(POSITIONAL_ID);
CREATE INDEX IX_VARIANT_VARIANT__REF_SNP_ID ON Variant.Variant USING HASH(REF_SNP_ID);
CREATE INDEX IX_VARIANT_VARIANT__BIN_INDEX ON Variant.Variant USING GIST(BIN_INDEX);
CREATE INDEX IX_VARIANT_VARIANT__POSITION ON Varaint.VARIANT(POSITION); 
CREATE INDEX IX_VARIANT_VARIANT__RUN_ID ON Variant.Variant(RUN_ID);
CREATE INDEX IX_VARIANT_VARIANT__EMBEDDING_RUN_ID ON Variant.Variant(EMBEDDING_RUN_ID);

-- TUNING INDEXES BUILT AFTER BIG LOAD, SEE create_variant_tuning_indexes.sql FILE
-- EMBEDDING INDEXES BUILD AFTER BIG LOAD, don't forget to make them partial (i.e., embedding not null)