-- table for variants

DROP TABLE IF EXISTS Variant.Variant CASCADE;

/* worth embedding 
functional_consequence
gene_context
regulatory_annotation
clinical_significance
literature_summary
pathway / ontology terms
*/

CREATE TABLE Variant.Variant (
    VARIANT_ID SERIAL NOT NULL,
    EXTERNAL_DATABASE_ID INTEGER NOT NULL,
    CHROMOSOME HumanGenome NOT NULL,
    POSITION INTEGER NOT NULL,
    SPAN INT4RANGE NOT NULL,
    REF_ALLELE TEXT,
    ALT_ALLELE TEXT,
    LENGTH INTEGER NOT NULL,
    BIN_INDEX LTREE NOT NULL,

    NIAGADS_ID CHARACTER VARYING(150) NOT NULL,
    NORMALIZED_POSITIONAL_ID TEXT,
    REF_SNP_ID CHARACTER VARYING(25),
    GA4GH_VRS JSONB NOT NULL,
    HGVS TEXT,

    VARIANT_CLASS CHARACTER VARYING(25) NOT NULL,
    IS_ADSP_VARIANT BOOLEAN,
    IS_STRUCTURAL_VARIANT BOOLEAN,
    IS_ANNOTATED BOOLEAN,

    LD_PARTNERS BYTEA,

    ADSP_ANNOTATION JSONB, --QC, FAVOR, ADSP MSC
    MOST_SEVERE_CONSEQUENCE JSONB,
    FUNCTIONAL_ANNOTATION JSONB, -- vep, etc
    ALLELE_FREQUENCY JSONB,
  
    -- AI generated summary + embeddings
    FUNCTIONAL_ANNOTATION_SUMMARY JSONB, 
    EMBEDDING_HASH BYTEA,
    EMBEDDING VECTOR(384),
    EMBEDDING_RUN_ID INTEGER,

    -- housekeeping
    RUN_ID INTEGER NOT NULL,
    CREATION_DATE TIMESTAMP NOT NULL DEFAULT NOW(),
    MODIFICATION_DATE TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY (VARIANT_ID, CHROMOSOME),
    FOREIGN KEY (RUN_ID) REFERENCES Admin.ETLRun(ETL_RUN_ID),
    FOREIGN KEY (EMBEDDING_RUN_ID) REFERENCES Admin.ETLRun(ETL_RUN_ID),
    FOREIGN KEY (EXTERNAL_DATABASE_ID) REFERENCES Reference.ExternalDatabase(EXTERNAL_DATABASE_ID)
) PARTITION BY LIST (CHROMOSOME);


SELECT variant.create_variant_partitions('variant.variant');

-- LOOKUP INDEXES
/* 
*/

