# FIXME: when moved to polylith project, use wheel based install
FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV STREAMLIT_SERVER_PORT=8501
ENV STREAMLIT_SERVER_ADDRESS=0.0.0.0
ENV POETRY_HOME=/opt/poetry
ENV PATH="/opt/poetry/bin:$PATH"
ENV POETRY_VIRTUALENVS_CREATE=false

WORKDIR /app

COPY pyproject.toml poetry.lock /app/
COPY bases /app/bases
COPY components /app/components
COPY development /app/development

RUN apt-get update \
    && apt-get install --no-install-recommends -y curl \
    && curl -sSL https://install.python-poetry.org | python3 - \
    && poetry install --no-interaction --no-ansi

CMD ["streamlit", "run", "development/chatbot_poc/app.py"]
