services:
  open-access-api-cachedb:
    # container_name: open-access-api
    # latest versions fails silently and stops the container; see https://github.com/Snapchat/KeyDB/issues/802
    image: eqalpha/keydb:x86_64_v6.3.3
    container_name: oaa-cachedb-${NAMESPACE}
    restart: always
    ports:
      - ${HOST_KEYDB_PORT}:6379
    # the bind 0.0.0.0 and protected-mode no allow it to be accessed by the host machine
    # need to re-evaluate for production deployment
    # note: multi-master requires active replication
    # command: keydb-server --multi-master yes --protected-mode no --bind 0.0.0.0
    command: keydb-server --protected-mode no --bind 0.0.0.0
    volumes:
      - ${KEYDB_DATA_DIR}:/data

  open-access-api-server:
      # container_name: open-access-api
      image: open-access-api-server:${API_VERSION}
      container_name: oaa-server-${NAMESPACE}
      build:
        context: .
        dockerfile: ./Dockerfile
        args:
          API_VERSION: ${API_VERSION}
          APP_MODULE: ${APP_MODULE}
      ports:
        - '${HOST_SERVICE_PORT}:8000'

      # network_mode: bridge
      # networks:
      #  - niagads-api_default

  # networks:
    #niagads-api_default:
    #    external: true